### ISSUE TITLE
Create a simulation of trading activity on testnet AlphaDEX

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#10]
Maybe creating a script that runs trades periodically, so that we would have nice explorable trade history.
Maybe for a couple of pairs.

**Comment by EvgeniiaVak** [comment]
I thought a little bit about how can we set it up. So what we need on testnet AlphaDEX is:

- some open orders existing
- some trading deals happening
- maybe periodic changes to all of that so that the activity would resemble a real life exchange 

So maybe it's like creating a couple of trading bots doing some random stuff? Feels a lot like testing AlphaDEX itself. Should certainly be interesting to people planning to do algo trading on Radix.

**Comment by EvgeniiaVak** [comment]
Or, if not implementing bot scripts, we can kindly ask our telegram community to periodically try out trading once we have something working on the testnet. Won't be as live and frequent as bots, but the upsides are:
1. we won't spend dev time on it - we already have enough on our plates and there are a couple non-dev people wanting to contribute somehow
2. the test will be closer to what we need to test - I bet they will find a couple of bugs for us early

**Comment by SmashingBumpkin** [comment]
That could be quite nice, but also might be a struggle to get people set up and running the dev environment and keeping them up to date with the latest changes. There's a lot to unpack there if you've never seed an IDE in your life!

All that effort would only really pay dividends if they made quite a commitment to sending txs fairly regularly, so pragmatically I'm not sure how much it would help.

**Comment by EvgeniiaVak** [comment]
Yes! That's the thing, github actions (or maybe vercel, with next.js in my experience vercel is easier) is awsome for this! We can set up the auto-deployment so that whenever we merge to main branch, it's automatically deployed to the dev. hosting (and it's super easy - look at this repo - https://github.com/EvgeniiaVak/order-book-demo )

**Comment by EvgeniiaVak** [comment]
So people wouldn't have to set up any dev environment, just go to the website (granted our current ugly version) and click buttons. But we need to do #36 first

**Comment by fliebenberg** [comment]
On the trading: I am planning to write a bot that provides liquidity on pairs, so it would not be too much of a stretch to also just make it do trades on a regular basis. But this will likely only happen towards September. I definitely agree that we should encourage the community to start manually trading on the app as soon as they can. People that do automated trading will not do it through our app, as they will interact either directly with the AlphaDEX components or API/SDK. But all those trades will still be shown on our app just like it will show trades that happen on other apps working on AlphaDEX.

Our aim should be to get an MVP out as soon as possible for the community to interact with and provide feedback. For an MVP we really only need to show the orderbook and have the ability to submit orders and maybe show open/completed orders for an account. The rest we can add as we finish it. That alone should generate some trades to show.

**Comment by EvgeniiaVak** [comment]
I agree, and I think we also can deploy not even MVP but even something more unfinished (after completing #6 ) - and share with the people so they can test the functionality even if the UI doe not meet any design plans.

**Comment by yuliaSharabi** [comment]
MVP is out, so it's irelevant.
FYI @fliebenberg @dcts

**Comment by dcts** [comment]
@yuliaSharabi we still use testnet during development so this issue still is relevant. 

But we can keep closed and create a new one once this comes up again. I think having more.data in testnet would still be valuable.
