### ISSUE TITLE
24h Change calculation appears incorrect

### ISSUE THREAD

**Issue by nguvictor** [DeXter-on-Radix/website#129]
The last price change % isn't correct
Previous price was around 40 
![image](https://github.com/DeXter-on-Radix/website/assets/3978285/cbe3441a-1655-40a1-85a6-4e68731c8d37)

Pushed price to 7, was expecting a different number
![image](https://github.com/DeXter-on-Radix/website/assets/3978285/4aa980f9-2bf1-4fb5-aedb-c219e7faf307)

**Comment by EvgeniiaVak** [comment]
@nguvictor this is a change from price 24 hours ago not from previous trade price, In this example what was the day ago price?
