### ISSUE TITLE
Successful transactions sometimes display as hanging

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#135]
Probably something to report on https://github.com/radixdlt/radix-dapp-toolkit repo rather than fixing ourselves. Sometimes the connect button does not display that the transaction already finished successfully (it did in the wallet). That also does not update our dexter state and as a result the order input submit button is still disabled (which is correct).

Reloading the page helps.

<img width="383" alt="Screenshot 2023-09-27 at 16 51 43" src="https://github.com/DeXter-on-Radix/website/assets/27793901/b460ca46-8678-4119-83f0-f6054faece30">
<img width="1470" alt="Screenshot 2023-09-27 at 16 49 32" src="https://github.com/DeXter-on-Radix/website/assets/27793901/f2e33bb7-6a8e-405f-9b93-f3b66d96529b">

**Comment by yuliaSharabi** [comment]
Not reproducible after Wallet+code changes.
