### ISSUE TITLE
Zeros in input fields cannot be deleted

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#138]
https://t.me/c/1988854086/1/489

> One thing I notices is that sometimes remains a 0 infront of the sum in the field when you type
> i can't delete the zero
> only if i select with the mouse the text and delete
> but place cursor there and try to delete characters doesn't work

<img width="300" alt="Screenshot 2023-09-27 at 18 52 46" src="https://github.com/DeXter-on-Radix/website/assets/27793901/d625308d-9214-49a2-8945-c84ff5a1ca99">

**Comment by nguvictor** [comment]
It looks like #117 likely addresses this issue, but it's still in the works atm.
