### ISSUE TITLE
Full Orderbook

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#151]
Currently Orderbook only shows 8 order prices closest to the market. We need to be able to show the whole orderbook somehow, maybe by aggregating the prices (with mouse scroll or via a selector somewhere on top of the orderbook).

**Comment by nguvictor** [comment]
Here is an example of what we could do, a type of grouping.
![orderbook](https://github.com/DeXter-on-Radix/website/assets/3978285/81545fba-fde9-47f6-9c3e-2d826e58878f)

**Comment by EvgeniiaVak** [comment]
This grouping is aggregating into price buckets, right?
Yes, looks good 👍  We probably won't have those extra options so we can just directly put the grouping interface on top of the orderbook (wtihout ⚙️ submenu) - less clicks

**Comment by nguvictor** [comment]
Yes, it's likely doing some type of client side or server side a aggregation into buckets.
