### ISSUE TITLE
Pair selector improvements

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#154]
- [x] search for pairs
- [ ] shortcuts: to start search, select on enter, cancel on esc 
- [x] auto-close when a pair is selected
- [ ] fix vertical alignment
- [x] (maybe) improve the background animation on click

**Comment by fliebenberg** [comment]
Another item to add to this issue: close the selector box when clicking on the dropdown arrow again. I.e. when arrow is clicked the first time the box is opened, when arrow is clicked again, the box should close. The arrow should toggle the open/close of the selector box.

**Comment by fliebenberg** [comment]
Could also fix #156 when working on this issue.

**Comment by EvgeniiaVak** [comment]
#156 is quicker and can be done sooner
