### ISSUE TITLE
Decide how we want to store state in the app.

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#16]
We need to decide how we want to store state in the app. Do we use UseState and context variables or do we use a state management framework?

**Comment by SmashingBumpkin** [comment]
Context variables sounds preferable, but I believe we will need to slightly restructure things. As it is at the moment page.tsx is not a child of layout.tsx, so I think they would need to be given a common parent to share state?

**Comment by EvgeniiaVak** [comment]
React context looks cool.

**Comment by muhammadraazy** [comment]
> I vote for useState hook to start with. If we hit the limits of its capabilities, then we look for a framework.

yeah, we can start with Context first, later on if needed we can using framework

**Comment by timanrebel** [comment]
From my experience it's best to start as simple as possible. I would use `useState` where state is only needed locally and use a `Context` when state needs to be shared between components.

During the development and scaling of the project some or even a lot needs to be refactored multiple time anyways to get it to work for all use cases, so we don't need to prematurely scale to more complicated frameworks

**Comment by Darab-gif** [comment]
I'll suggest we should completely use framework (ReduxJs) so as to reduce the stress of restructuring

**Comment by muhammadraazy** [comment]
Im okay both with Context or Redux guys

**Comment by EvgeniiaVak** [comment]
> I'll suggest we should completely use framework (ReduxJs) so as to reduce the stress of restructuring

yeah, but then we would feel the stress of redux for sure 😅 while restructuring might not even need to happen (react context API looks powerful enough at first sight)

**Comment by fliebenberg** [comment]
Im also in favour of trying to only use usestate or context for now. If we find cases where we need more complicated state management, we can start switching over to that. usestate/context can still be used if we decide to switch to a state framework and we can then do the switchover gradually. So I vote to keep it as simple as possible for now.

**Comment by EvgeniiaVak** [comment]
Looks like useState + useContext won.
