### ISSUE TITLE
Dependencies update causes connect button to sign out in dev mode

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#173]
The connect button logs me out every time I reload the page. 

looks like an update to some lib causes it, here is how I found out: #148 
before I ran npm audit fix (without force flag) everything works ok, I'm still logged in on an old version (even if I install the old version afterwards, the same page shows me as logged in), but once I run npm audit fix (which results in the update of libs shown in the diff on the link), the connect button starts to log me out on every reload
only happens locally during development (npm run dev), the deployed preview stays logged in after reload

related discord discussion with radix - https://discord.com/channels/417762285172555786/1160487885988970596

```
% npm audit
# npm audit report

@babel/traverse  <7.23.2
Severity: critical
Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code - https://github.com/advisories/GHSA-67hx-6x53-jw92
fix available via `npm audit fix`
node_modules/@babel/traverse

next  <=13.5.4-canary.11
Severity: moderate
Next.js missing cache-control header may lead to CDN caching empty reply - https://github.com/advisories/GHSA-c59h-r6p8-q9wc
Depends on vulnerable versions of postcss
Depends on vulnerable versions of zod
fix available via `npm audit fix`
node_modules/next

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix --force`
Will install postcss@8.4.31, which is outside the stated dependency range
node_modules/next/node_modules/postcss
node_modules/postcss

zod  <=3.22.2
Zod denial of service vulnerability - https://github.com/advisories/GHSA-m95q-7qp3-xv42
fix available via `npm audit fix`
node_modules/next/node_modules/zod
node_modules/zod

4 vulnerabilities (1 low, 2 moderate, 1 critical)
```

**Comment by nguvictor** [comment]
This has been delayed, because of issue in the radix dapp toolkit. The issue is being worked on here: 
https://discord.com/channels/417762285172555786/1174712460675129474

**Comment by EvgeniiaVak** [comment]
the new connect button now connects all right with new next.js, but there is another problem the subscriptions are not working - https://discord.com/channels/417762285172555786/1018955196786823188/1181329944811413555 investigating...
