### ISSUE TITLE
Approved pair list

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#176]

**Comment by fliebenberg** [comment]
I think this issue has also been addressed already when we implemented the "whitelist" of pairs for Dexter. Happy to remove this issue.

**Comment by dcts** [comment]
Our current logic is that we only have a removelist for deprecated coins, but do not have an actively managed allowlist. So currently its permissionless. 

I think we should have a logic to review coins and have an allowlist. I started working on a proposal but havent followed up on it as it does not seem like a pressing issue. 

I agree we can close this and re-open once we run into this issue again.
