### ISSUE TITLE
Fix UI for smaller screen sizes

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#181]
Since the mobile browsers are not yet supported by Radix this issue is more about narrow screens on desktops. 

![photo_2023-11-14 20 04 21](https://github.com/DeXter-on-Radix/website/assets/27793901/ca7970cb-1b5c-4c8b-91b7-5cb35b4f7ecd)

for example window.innerWidth = 1006

![Screenshot 2023-11-14 at 19 47 03](https://github.com/DeXter-on-Radix/website/assets/27793901/d9f850d5-a229-485c-83a3-f9d5e338cc1c)

or width 1041

![Screenshot 2023-11-14 at 20 11 54](https://github.com/DeXter-on-Radix/website/assets/27793901/70d7ca26-7ed2-4285-a022-f3c308f5b986)

**Comment by EvgeniiaVak** [comment]
ok, this one is proving to be harder than I thought, postponing it as I finally got the access to the wallet and can now fix some more pressing issues


so far I had this in page.tsx (but canvas in price chart for some reason breaks everything when resizing the window):

```tsx
  return (
    <div className="col-span-12 grid bg-base-300 space-x-1 space-y-1">
      <div className="col-span-6 xl:col-span-3 order-1 xl:order-1 bg-base-200">
        <div>
          <PairSelector />
        </div>
        <div>
          <OrderInput />
        </div>
      </div>

      <div className="col-span-12 xl:col-span-6 order-2 flex flex-col bg-base-200">
        <div>
          <PriceInfo />
        </div>
        <div>
          <PriceChart />
        </div>
      </div>

      <div className="col-span-6 xl:col-span-3 order-1 xl:order-3 bg-base-200">
        <OrderBook />
      </div>

      <div className="col-span-12 order-4">
        <AccountHistory />
      </div>
    </div>
  );
```

**Comment by fliebenberg** [comment]
Agree that this issue is now irrelevant as we have implemented differentiated design for mobile. Happy to remove this issue.
