### ISSUE TITLE
Add "Runs on Radix" to footer

### ISSUE THREAD

**Issue by nguvictor** [DeXter-on-Radix/website#183]
Related to Telegram suggestion:
https://t.me/c/1988854086/1/812

**Comment by rianmanhente** [comment]
I will do this one

**Comment by rianmanhente** [comment]
the discussion is not available for me

**Comment by rianmanhente** [comment]
apparently this issue has already been made

**Comment by nguvictor** [comment]
Yep, the issue is still open if you want to make a PR
