### ISSUE TITLE
Best buy/sell and orderbook decimals are not displayed

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#187]
Orderbook prices need to be shown to more decimals (just show full allowed decimals). Currently it looks like the best buy and sell prices are the same because not all decimals are displayed. E.g. XRD-TUSD pair is showing 0.05 best BUY price (actual 0.05) and 0.05 best SELL price (actual 0.05005).

**Comment by nguvictor** [comment]
I was thinking we go to 8 decimal places as a general standard as it makes it easier to handle the ui. If we went down to 18 decimal places, it might make it tough to prevent wrapping. Would be good to see what other suggestions people have on standardizing this.

**Comment by EvgeniiaVak** [comment]
if there are some tokens for which many decimal places are important we need to redesign somehow to fit them all in
