### ISSUE TITLE
No error message on failed getting Quote

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#196]
![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/1e37918c-809f-4681-a5f5-c22b22b5b45d)

**Comment by EvgeniiaVak** [comment]
cannot reproduce this one, I guess we need to have a pair with no orders in the orderbook (at least on one side) to be able to reproduce

**Comment by dcts** [comment]
Old design, not relevant anymore.
