### ISSUE TITLE
Agree on the framework 

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#2]
If we go with the implementation with code, what frame will we use? (E.g. React, Svelte, Vue, etc)

**Comment by fliebenberg** [comment]
Maybe we can all add what frameworks we can program in together with a rating of our skill level (3 expert, 2 intermediate, 1 beginner)
Angular (3), React (1), Svelte (1)

**Comment by EvgeniiaVak** [comment]
Another point to consider while choosing the framework is the **mobile app**.

While I don't think the mobile app should be in the MVP (better to focus on a responsive web page, that is usable on all devices first) we still should consider it happening probably somewhere down the road. I don't know much about mobile development, but my hunch is React will be easier (because there is [React Native](https://reactnative.dev/)), but there is also [NativeScript](https://nativescript.org/) project that seems to support any framework.

**Comment by EvgeniiaVak** [comment]
@SmashingBumpkin would you like to weigh in on that? What's your preferred framework?

**Comment by EvgeniiaVak** [comment]
Also, react / svelte care mostly about JS/TS (I strongly prefer TS by the way), to make the creation of elements simple, I suggest using https://daisyui.com/ (that also implies tailwind.css), and then adding some custom CSS to each element if we need something special, and try to not using extra component libraries.

**Comment by EvgeniiaVak** [comment]
I'm going to proceed with React (and Next.js). If anybody is against this, please reopen the issue.
