### ISSUE TITLE
Old quote is not removed when input is 0

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#200]
https://github.com/DeXter-on-Radix/website/assets/27793901/470a16ac-621e-4670-a5ec-14e92721f38c

**Comment by nguvictor** [comment]
Doesn't look like this is an issue anymore after we cleared the input/validation. @EvgeniiaVak 
![fees](https://github.com/DeXter-on-Radix/website/assets/3978285/ae3fd877-24da-4959-971b-3a1c32387041)
