### ISSUE TITLE
Order input validation messages shift layout

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#204]
Maybe a minor issue (need to check what ui/ux people think of it). When There is an error message it shifts the layout down. 
<img width="1470" alt="Screenshot 2024-01-22 at 11 51 17" src="https://github.com/DeXter-on-Radix/website/assets/27793901/1cd8c76b-c999-41ba-8a73-ee985e201f27">
<img width="1470" alt="Screenshot 2024-01-22 at 12 06 17" src="https://github.com/DeXter-on-Radix/website/assets/27793901/fa509868-3e13-4fa7-b34f-01e3fbc8c24a">

**Comment by yuliaSharabi** [comment]
Can you add issue description, so it will eb clear later on how to test it?

**Comment by dcts** [comment]
I'm curious, what would be the desired behavior when shifting the UI is not an option?

**Comment by dcts** [comment]
Implementing Toasts as described in #77 might be a good fix for this, although what I don't like bout the toast, is that the message eventually disappears, whereas in the current approach, the error message just stays until fixed, which IMO is better UX.

**Comment by EvgeniiaVak** [comment]
> I'm curious, what would be the desired behavior when shifting the UI is not an option?

Yeah, that needs some thought. 

My first idea would be to show the first X (how many - needs some playing around) letters and `...` and on hover we could show a tooltip with the whole text.

Or maybe just leaving more empty space there from the start... probably will not look good though.

Or maybe do nothing and it's better as it is now.

**Comment by dcts** [comment]
Another solve might be a tooltip that appears as long as the error is not resolved, for example like this (seen on Binance):
<img width="340" alt="Bildschirmfoto 2024-03-04 um 18 02 33" src="https://github.com/DeXter-on-Radix/website/assets/44790691/f9406dcc-1b65-4e22-b24f-f688168a7790">
