### ISSUE TITLE
[Mainnet]TRADE button is redundent 

### ISSUE THREAD

**Issue by yuliaSharabi** [DeXter-on-Radix/website#217]
Summary:

*Steps to Reproduce:*
Click on the TRADE button and on the Dexter button 

*Expected Behavior:*
NOT sure why we need the TRADE button then?

*Actual Behavior:*
Both navigate to the URL dexteronradix.com

*Environment:*
mainnet

*Severity:*
low

*Attachments:*
![image](https://github.com/DeXter-on-Radix/website/assets/22341165/b36225c7-cacc-4209-a647-ec917cb8ceb6)

**Comment by EvgeniiaVak** [comment]
@yuliaSharabi we are cooking up an update with MARKETS page link in the nav bar (`dexteronradix.com/markets`). Also there will be (but even later) a landing page on `dexteronradix.com` and the trade will move to `dexteronradix.com/trade`. Currently there are only 2 pages - index (which contains what will be /trade in the future) and /terms (link in the footer). You can navigate to the trading page from /terms page both in the navbar and in the footer. It's a bit silly to have TRADE right now in the nav bar, but it will make more sense with the MARKETS page update.
