### ISSUE TITLE
Buy/Sell Panel UI Improvement suggestion

### ISSUE THREAD

**Issue by Radstakes** [DeXter-on-Radix/website#220]
![image](https://github.com/DeXter-on-Radix/website/assets/83462165/d524f58f-e895-411b-8db7-8a6756163520)
![image](https://github.com/DeXter-on-Radix/website/assets/83462165/1f1166ed-a14b-47f7-94ae-5063e89d17ae)

**Comment by dcts** [comment]
This is deprecated.
