### ISSUE TITLE
Order price in Open Orders table showing wrong token name

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#234]
In the Open Orders (and also Order History) table the Order Price column shows the wrong token symbol.

![image](https://github.com/DeXter-on-Radix/website/assets/30161217/e3da7eb4-1b67-4a90-b336-3aedf0a7bb99) 
In the example above the price should be in XRD, not DEXTR.

**Comment by dcts** [comment]
I noticed this too. Is anyone working on this or can I fix this?
