### ISSUE TITLE
Add pair "Trades" table

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#235]
On most CEXs, you can see a list of the last few trades that have happened in that pair (all trades, not just trades of the user). This is useful for traders as it gives them an idea at which prices recent trades have been happening. This is especially relevant for pairs where trades happen more frequently than what is shown in the candle graphs.

The table could just have 3 cols:
Time - the time of the trade
Price - the price at which the trade settled
Amount - the amount of token1 that was traded

Each line in the table could also be colored green or red to indicate if the trade was a buy or a sell.

The information for this table is already available in the AlphaDEX sdk "state.currentPairTrades" variable. You will just need to calculate price as token2Amount / token1Amount and rounded to priceMaxDecimals for the pair.

This feature will also require some design to decide where to place it on the UI

**Comment by nguvictor** [comment]
This was resolved
