### ISSUE TITLE
A popup with pair options in some browsers

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#237]
https://github.com/DeXter-on-Radix/website/pull/236#issuecomment-1913449850

**Comment by EvgeniiaVak** [comment]
@nguvictor I can't reproduce it (brave browser, macos), this pop up does not appear for me if I enter / or just click on it. Maybe there are some steps?

**Comment by nguvictor** [comment]
Let me try reproducing over the weekend, maybe it's an edge case lingering from development. If I'm unable to reproduce then let's say it's resolved.

Worst case it's just adding
 ```
autocomplete=false
```
To the input

Reference:
https://www.w3schools.com/tags/att_input_autocomplete.asp

**Comment by nguvictor** [comment]
After clearing autofill I wasn't able to reproduce, might of just been a lingering item from development
