### ISSUE TITLE
A not-good-looking border on chart period selector

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#240]
Steps to reproduce (in chrome browser):
- select a new time period
- press `esc`

![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/f07f7465-f73c-4d8a-93e2-0589fd075cd5)

**Comment by dcts** [comment]
@EvgeniiaVak what would you expect to happen after clicking `esc`?

(A) no border shows
(B) a border shows on all 4 sides

**Comment by dcts** [comment]
@EvgeniiaVak I did some research and it is indeed there for accessibility reasons, so I would highly recommend keeping it. Submitted a [PR](https://github.com/DeXter-on-Radix/website/pull/242) for it and added more context there.
