### ISSUE TITLE
White and black runs-on-radix + runs-on-alphadex buttons on footer

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#246]
I would keep them simple if you want to add the labels. 
To have them both just white on black. Radix has a version like that. 
Otherwise I think it gets too "flower power" the whole footer.

_Originally posted by @Kafkafrate in https://github.com/DeXter-on-Radix/website/issues/244#issuecomment-1923395837_

**Comment by EvgeniiaVak** [comment]
Blocked atm, we don't have an AlphaDEX styled button yet.

**Comment by dcts** [comment]
new footer design does not contain any of those buttons, but when they become available we might want to add them dependant on @maurojose design vision :)

![image](https://github.com/DeXter-on-Radix/website/assets/44790691/b2b19646-3e0a-47d5-87d0-6cc5ca41bb35)

**Comment by EvgeniiaVak** [comment]
> new footer design does not contain any of those buttons, but when they become available we might want to add them dependant on @maurojose design vision :)
> 
> ![image](https://private-user-images.githubusercontent.com/44790691/322233684-b2b19646-3e0a-47d5-87d0-6cc5ca41bb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDAwNTUsIm5iZiI6MTcxMzMzOTc1NSwicGF0aCI6Ii80NDc5MDY5MS8zMjIyMzM2ODQtYjJiMTk2NDYtM2UwYS00N2Q1LTg3ZDAtNmNjNWNhNDFiYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3NDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzVlZDk0ODE1MDk4Zjc5OGMxZjFlM2U4M2VlNWU1M2QxZjVlMWU5OTJhYmMyOGExN2ZmMzliNTdhZDc5ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.viF37vixzFmyigm39t5Dq8whmwgQX7smzbkQxe8B09M)
