### ISSUE TITLE
Cannot connect to radix wallet on loacalhost

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#250]
I'm still experiencing issues connecting my Radix wallet (Android) to Dexter running on localhost. Here's what I've tried:

1. Uninstalled Radix Connector and Radix Wallet.
2. Reinstalled Radix Wallet on Android, switched to Stokkenet testnet, and enabled developer mode.
3. Reinstalled the Chrome Connector extension and connected it with my Radix Wallet app.
4. Ran `npm run dev`.
5. Opened localhost:3000, clicked the "Connect" button in the top right corner.
6. Immediately received the error message in my wallet app: "Invalid Request. Could not validate the dApp," despite having developer mode enabled, which should disable website validity checks.

Interestingly, everything works when I open a deploy-preview from Netlify, like [this one](https://deploy-preview-238--chipper-sunburst-578cfe.netlify.app/).

**Enviroment**
OS: Ubuntu 22.04 LTS
browser: brave browser (runs on chromium)
radix wallet app version: 1.4.0
chrome connector extension version: 1.3.6

When I try the same thing on chrome browser, I don't even get an error message, simply a login request that is stuck without any notification whatsoever on my radix wallet app, both on localhost and on netlify but also on dexteronradix.com. 

Side note: I had issues with the radix app before, see this issue: https://github.com/radixdlt/babylon-wallet-android/issues/704
Also radix officially does not support brave browser.

Can any developers confirm whether they can connect to their Radix wallet on Stokkenet via localhost?

If you have any ideas how to fix please LMK!

**Comment by dcts** [comment]
Forwarding my localhost to a public URL with ngrok lead to the same error as on localhost. Really weird, so it has not to do with where it's hosted, but actually the hosting machine itself (I suspect).

**Comment by nguvictor** [comment]
I'm using Brave Browser on a Windows 11 Machine on Radix Wallet Connector 1.3.2 (Dev Tools)
![image](https://github.com/DeXter-on-Radix/website/assets/3978285/656a4a8e-835f-4e37-a5f4-fe0f08fdb656)

Maybe give a different connector version a try?

**Comment by dcts** [comment]
Solved by updating chrome to newest version (on linux this is not trivial unfortunately).

Leaving this as a future reference or in case someone runs into the same issue.

### How to update chrome to newest version using linux (e.g. ubuntu 22.04)
```
# Run the following commands one by one to add the repository and install Chrome:
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt update
sudo apt install google-chrome-stable
```
