### ISSUE TITLE
Order History redesign

### ISSUE THREAD

**Issue by nguvictor** [DeXter-on-Radix/website#259]
Order history needs redesign, there are multiple issues to take into account.

---

One of the issues:
Looks like that Order History isn't organized by time completed, might be a helpful enhancement to order either descending and ascending.
![image](https://github.com/DeXter-on-Radix/website/assets/3978285/523fb04f-8016-488d-89cd-fa2f47173f9c)

**Comment by dcts** [comment]
@nguvictor I cannot reproduce this. Some questions:
- for which table does this occur (Open Orders, Order History or Trade History)?
- can you show the full table (obviously feel free to remove any sensitive information), but it might help to find a pattern (for example it might be ordered by amount or price etc)
- if not too much of an ask: can you create a reproducable example on testnet (e.g. market buy X, then market buy Y, then do that -> then the bug occurs).

We could also just order all entries by date and see if that fixes your issue, but might be worth exploring the root of the bug, as we might find other bugs by doing so. :)

**Comment by nguvictor** [comment]
Its on the trade history tab

My hunch is it's listing ascending by the id of the receipt nft vs the completed time.

I'll take a screenshot of the network tab later tonight. If you need more info
