### ISSUE TITLE
the "trade" link at the bottom of the website

### ISSUE THREAD

**Issue by ironladyxrd** [DeXter-on-Radix/website#265]
It looks like the "trade" link at the bottom of the website and the title of the social media channels under this link. For this reason, the trade link should be removed from here
![Social Media Channels   Trade link](https://github.com/DeXter-on-Radix/website/assets/159444870/c0976cdc-4543-4417-914c-2c371add0c6d)

**Comment by dcts** [comment]
I noticed this too. The only practical use case I see for this link is on mobile, if the user reaches the bottom of the page, its an easy shortcut to go to the top of the page again. 

Maybe @EvgeniiaVak can add some more context? :)

**Comment by EvgeniiaVak** [comment]
@dcts it was in some version of the figma design, not sure if it's still there, I don't have any comments on having or not having it there, I think the intention was to duplicate all the links from navbar here (markets page, etc)

**Comment by EvgeniiaVak** [comment]
@dcts I'm not a designer, and I don't have a strong opinion here. To me it looks fine the way it is right now and when there are more links it will probably be more useful to have them both in navbar and on footer. I don't think we need titles for the social icons - they look quite self-explanatory.
