### ISSUE TITLE
Make pair search more intuitive

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#267]
# Problem

The current search functionality in the pair selector component only matches exact strings, resulting in a subpar user experience. Users expect a more advanced search experience similar to Google, including typo tolerance, partial matches, and the ability to search by either symbol or token name.

# Your Task

Enhance the search feature to make it more intuitive by implementing the following:
- Allow spaces as delimiters instead of requiring "/"
- Ensure the order of inputted coins does not matter (e.g., "XRD DEXTR" should match "DEXTR/XRD")
- Support both symbol and full name searches (e.g., searching for "Radix" should return all pairs involving "XRD")
- Make the search case insensitive (e.g., "XrD" should match "XRD")
- (if you want) Include minimal typo tolerance (e.g., allow one typo for every 5 characters)
(feel free to add other usecases if you find that some are missing)

# Implementation hints

Define the following function inside utils.ts:

```ts
export function searchPairs(query:string, pairsList: PairInfo[]): PairInfo[] {
  // Your implementation
}
```

## Tests

Ensure your implementation passes the following Jest test cases (generated by chatGPT without review, please modify the test cases as you see fit, this is only a starting point):

```ts
describe('searchPairs', () => {
  // example initialization, feel free to change and copy actual pairsList data for more realistic results
  const pairsList: PairInfo[] = [
    {
      name: "DEXTR/XRD",
      token1: { name: "Dexter", symbol: "DEXTR" },
      token2: { name: "Radix", symbol: "XRD" },
    },
    {
      name: "BTC/ETH",
      token1: { name: "Bitcoin", symbol: "BTC" },
      token2: { name: "Ethereum", symbol: "ETH" },
    },
    {
      name: "ADA/XRD",
      token1: { name: "Cardano", symbol: "ADA" },
      token2: { name: "Radix", symbol: "XRD" },
    },
  ];
  test('should find pairs by full name', () => {});
  test('should find pairs by symbol', () => {});
  test('should find pairs by symbol and full name with different case', () => {});
  test('should find pairs with space as delimiter', () => {});
  test('should find pairs with swapped order of tokens', () => {});
  test('should handle minimal typos', () => {});
  test('should return an empty array if no matches are found', () => {});
});
```

Then filter search results by modifying `onQueryChange` function here:
[onQueryChange](https://github.com/DeXter-on-Radix/website/blob/39060d8fe61296da96542534d3f8028b16792738/src/app/components/PairSelector.tsx#L163-L176)

**Comment by saidam90** [comment]
✋🏼
