### ISSUE TITLE
Pair selector selects wrong pairs on mobile

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#268]
On mobile, the pair selector sometimes selects the wrong pair. 

To reproduce:
- open dexteronradix in the browser, open devtools, chose mobile view (alternatively, use your phone)
- click pair selector
- select FLOOP - XRD
- the pair DCG - XRD is selected instead. 

It cannot be a misclick due to narrow elements, as `DCG - XRD` pair is not even a neighbor of `FLOOP - XRD` pair. It looks like it just selects the first pair. But it doesnt do that consistently. As a rough estimate, selecting a pair on mobile only works in about 50% of the tries.

![bug](https://github.com/DeXter-on-Radix/website/assets/44790691/47f2b379-bca2-456d-a0e2-52ed802fba07)

**Comment by nguvictor** [comment]
I was able to reproduce this as well. 
![mobile](https://github.com/DeXter-on-Radix/website/assets/3978285/7570d3a7-207f-401b-96ab-73c7a8cca72c)
