### ISSUE TITLE
Console errors on pageload

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#283]
We should fix those console errors, they happen on every pageload:

![Bildschirmfoto vom 2024-03-08 16-28-13](https://github.com/DeXter-on-Radix/website/assets/44790691/25c3195d-1750-46ff-89ec-6323e56a133d)

**Comment by dcts** [comment]
To me it looks like this is already resolved even without #577. At least I don't see any errors in the console when checking the live app at dexteronradix.com. 

@SiegfriedBz please re-open if you still can reproduce these errors.

**Comment by SiegfriedBz** [comment]
@dcts 
actually I decided to implement the error.tsx file when I saw the  #283 issue
but I couldn t reproduce specifically the  #283 issue
I believe an error.tsx file is best practice to handle unexpected runtime errors and display a fallback UI, independently of the  #283 issue depicted here
