### ISSUE TITLE
Investigate what charting lib to use

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#3]
Whether we go with no-code or code solution for the whole website, we need to include the charts on the page. The main 2 charts so far are candlestick price and depth of market (or order book). 

---

live charts demo - https://evgeniiavak.github.io/order-book-demo/  

---

### Related comments from our telegram history:

free tradingview version only has the price charts, if we want Depth of Market (DOM) - it comes with their "Charting & Trading Platform" (the paid version).
And it looks like we want the depth as the first feature according to the poll results so far https://strawpoll.com/wAg3A73qly8/results

charting libraries are a mess. The problem with trading view is that it has also too much to it, so when you want to customise and simplify it is a nightmare. Plus it has some strange behaviour on zoom in zoom out, etc. We tried to do it on our Stream wallet app but endd up taking a more simple one and customise. 
Now on a DEX you need more complexity, but I suppose until you don't try and see you will not know what's best.

**Comment by EvgeniiaVak** [comment]
I'm experimenting with using no lib at all, how difficult it will be to create and maintain, will push updates here.

**Comment by EvgeniiaVak** [comment]
While custom-made candlestick charts are fun, they take a lot of time to compose. I suggest we go with Tradingview at least lightweight charts, that are open source, they are quite easy to include on the page https://evgeniiavak.github.io/order-book-demo/tradingview-candlestick

as for other tradingview libs that have more functionality (for example the depth chart) we would need their pro version. Unfortunately their plans listed here https://www.tradingview.com/gopro/#plans are for using their widget together with their data. What we need is here https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/ and it requires some registration and quite possibly some payment:



![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/0c57c9e8-f3a2-43a7-9252-d6efeec60c1e)



I will play with the lightweight charts to see if this version is enough for us. Things to check:
- [x] adjustable themes (yes)
- [ ] on hover details
- [ ] something else?

**Comment by Kafkafrate** [comment]
I think if we manage to work with the free/lightweight version for the main candlestick chart and use your custom made depth chart, we're good. 

For the orders table I suppose we can do it with html+css? like the rest of the UI.

**Comment by EvgeniiaVak** [comment]
Looks like free tradingview + everyting else in plain html+css will be enough, I tried a couple of more features and everything works and is easily usable ([here](https://evgeniiavak.github.io/order-book-demo/tradingview-candlestick) is the updated chart with an order marker and volume under the ohlc), some customization options are absent, but I hope we will not need them.

**Comment by fliebenberg** [comment]
The free version looks great. We wont need anything else for now. Once the app is up and running, we will have a better idea of which features we still need on the paid version (or other solution).
