### ISSUE TITLE
Change for Portuguese translation of Cancel

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#301]
Message from Telegram: https://t.me/dexter_discussion/13080

Asked to change translation of Cancel to "Cancelar"

**Comment by dcts** [comment]
Side note: For future reference translation issues can be submitted here :):
https://docs.google.com/document/d/11I9c3XjKPmXgc9V6puznD_mSXA5QCqNKAG1QCcClkRw/edit?usp=sharing

**Comment by dcts** [comment]
Closing as fixed by #308
