### ISSUE TITLE
Overlapping text in oderbook (in PT)

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#307]
<img width="526" alt="Bildschirmfoto 2024-03-20 um 18 16 19" src="https://github.com/DeXter-on-Radix/website/assets/44790691/6645d7f5-9d23-4368-b98f-601d5df3364c">

### To reproduce:
- select PT language in the top right corner
- reduce screensize until the text in the orderbook overlaps

### Fix

A fix could be to make the [text-overlow: elipsis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow), that way it would cutoff the text and show "..." instead of overlapping.

**Comment by MohitKambli** [comment]
Hello.
Hope you're doing well.
I would like to work on this issue.

Thanks and Regards,
Mohit Kambli

**Comment by dcts** [comment]
Awesome, I assigned you! Feel free to reach out on discord (https://discord.gg/Y44jqe2q2W) in the dev channel if you have any questions about the codebase, happy to help!

**Comment by dcts** [comment]
This was already fixed by translation changes (making the translation more concise).
