### ISSUE TITLE
Implement new Design System

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#325]
The new design system by @maurojose needs to be properly implementation. This will help iterating on the design system in the future. Ideally we want to have style system defined in a single file for the full repository.

Things to do:
- add new colors (currently we have green, dexterGreen, red. The new design only has 2 main colors: dexterGreen, dexterRed)
- adapt text elements (e.g. make h1 title have a gradient as in the designs)
- toaster stylings should be taken from daisyUI color configs, not hardcoded

Figma file with design system:
https://www.figma.com/file/Zjff03BX35fREatqzcWDS7/DeXter%20UI?type=design&fuid=708572579352018658

**Comment by EvgeniiaVak** [comment]
whoever implements this, please search the codebase thoroughly for instances of custom colors and sizes and fix them, I notice a lot of them in the #312 and probably there are more such instances

**Comment by dcts** [comment]
Resolved by #431
