### ISSUE TITLE
Bug: Cancelled order showing as PENDING

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#326]
I have the following chancelled order (on stokenet):
https://stokenet-dashboard.radixdlt.com/nft/resource_tdx_2_1ng6vf9g4d30dw8h6h4t2t6e3mfxrhpw8d0n5dkpzh4xaqzqha57cd2%3A%23242%23

On dexter it shows as "PENDING", although the order is cancelled on the NFT receipt. I am not sure where this error is coming from, but since I don't see any manipulation of the orders in our frontend app, I suspect it might be a bug in `adex.getAccountOrders`. 

**Stokenet dashboard**
![image](https://github.com/DeXter-on-Radix/website/assets/44790691/58213c0a-6056-4b26-bc38-f7ecf1f91c3b)

**Dexter Console**
![image](https://github.com/DeXter-on-Radix/website/assets/44790691/e199fb95-0eb0-4fc3-a071-9e0bd0d21d34)

**Dexter UI**
![image](https://github.com/DeXter-on-Radix/website/assets/44790691/e452669f-60a6-4288-8178-af90cdd996c9)

**Comment by fliebenberg** [comment]
This was a known bug on the alphadex backend server (which feeds the api and sdk). I have fixed it (I think), but forgot to also update the stokenet server with the change. I have updated it now, so it should be fixed.
You can maybe just check and let me know if it is still there.

**Comment by dcts** [comment]
Yes the issue is now resolved, thank you! :)
