### ISSUE TITLE
Direct URL access to specific trade pairs on Dexter

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#354]
As we onboard more projects, enabling URL sharing that directly opens a specified trade pair on Dexter could enhance user convenience by eliminating the need to search for a coin manually. This feature would allow projects to link directly from their websites to their specific trading pair on Dexter.

Implementation could either encode the trade pair as path (my prefered solution) or add it as query param, e.g.:
- `dexteronradix.com/trade/dextr-xrd`
- `dexteronradix.com/trade?pair=dextr-xrd`

**Comment by fliebenberg** [comment]
I also prefer the path option. This feature has often been requested.
