### ISSUE TITLE
Remove console logs for rewards components

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#369]
Some console logs were left in the code when adding the claim rewards functionality to make debugging easier if users encounter issues. These logs must be removed once the claim component has been running without issue for  a couple of days.

**Comment by mademoiselle-chantal** [comment]
Hello, @fliebenberg. I want to work on this issue.

**Comment by fliebenberg** [comment]
Hi. Welcome and it is great that you want to start contributing. As I explained in the description we just need to wait until the claims component has been merged with the main branch and it is working fine before we remove the logs. For now we want to keep the logs to help with any user issues if they arise.
I will comment in this issue again once we can go ahead.

**Comment by mademoiselle-chantal** [comment]
> Hi. Welcome and it is great that you want to start contributing. As I explained in the description we just need to wait until the claims component has been merged with the main branch and it is working fine before we remove the logs. For now we want to keep the logs to help with any user issues if they arise. I will comment in this issue again once we can go ahead.

Understood. Otherwise, thank you for your feedback.

**Comment by mademoiselle-chantal** [comment]
Hello, @fliebenberg. The PR for this issue is ready. Please, tell me if l did anything wrong and I'll be here to make any changes. Thank you.

**Comment by yuliaSharabi** [comment]
@fliebenberg Can we proceed with the PR merge? I think we pretty have seen that this works fine by now :)

**Comment by dcts** [comment]
> @fliebenberg Can we proceed with the PR merge? I think we pretty have seen that this works fine by now :)

This was already resolved in #402 so this issue can be closed.
