### ISSUE TITLE
What license to use for the code?

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#37]

**Comment by fliebenberg** [comment]
Ill have a look at this and come back with suggestions to consider. It is probably something we will need to take to the community for a decision. But we can discuss here once I have a bit more info.

**Comment by fliebenberg** [comment]
Have started a discussion on telegram about this. My preference is for a GPL type license, which basically says our software is open source and anyone can use it, as long as they then also make their code open source under the same license. Looking forward to see what the community thinks.

**Comment by dcts** [comment]
What's the status on this @fliebenberg ? Your suggestion makes a lot of sense to me, if we decide to move forward I can quickly do some research and add it. Although not high priority IMO, in the long run having license clarity for an open source project sounds important.

**Comment by dcts** [comment]
Replaced by #493
