### ISSUE TITLE
Trading Pair List Overflow

### ISSUE THREAD

**Issue by Radstakes** [DeXter-on-Radix/website#381]
![image](https://github.com/DeXter-on-Radix/website/assets/83462165/fe32d074-16eb-4c6e-bc35-88b84ba410ef)

Noticed this issue today, the last item in the list for me (XRD/xUSDC) doesn't fit the column. It's fine if I zoom out so must be specific to my display size/resolution.

**Additional information:**

- Brave (Chromium)
- Windows
- 1366x615px aspect ratio

**Comment by fliebenberg** [comment]
We need to have a max-length on the selection box and allow the user to scroll to see pairs lower down. We then also need to sort the pairs by trade volume to make sure we show the most active pairs at the top.

**Comment by dcts** [comment]
I assigned @restylianos as he already solved this issue with PR #421(to prevent someone else implemeting the same fix)

The sorting by volume is tracked in a separate issue #419

**Comment by restylianos** [comment]
Closing since this was resolved in https://github.com/DeXter-on-Radix/website/pull/421
