### ISSUE TITLE
Rewards page container has gaps on ultra wide screens

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#390]
The rewards page has gaps when rendered on an ultra wide screen, it looks like this:

![image](https://github.com/DeXter-on-Radix/website/assets/44790691/8d22d664-be5c-44c0-8d77-633a6c4f6272)

Ideally the container should fill the full screen until navbar and footer is reached (as indeicated by the red arrows). 

# To reproduce:
- run locally and open /rewards page
- go to devtools
- create a custom device and set resolution to 2200 x 1300: 
![image](https://github.com/DeXter-on-Radix/website/assets/44790691/a42755d6-4b6d-40ea-b944-b081a92a889a)

**Comment by Anureng** [comment]
Can i work on this ??

**Comment by dcts** [comment]
> Can i work on this ??

Yes sure! I assigned you to the issue. Be sure to create a new branch on your forked repository (not main).

**Comment by Anureng** [comment]
![Screenshot 2024-05-11 193259](https://github.com/DeXter-on-Radix/website/assets/88523354/b1a7b1f4-cf36-488c-bf24-a26da02950af)
is this ok ??

**Comment by dcts** [comment]
> is this ok ??

@Anureng Yeah looks good! Did you check if the other page (Trade) did not break? Feel free to submit PR so we can take a look at the code. :)

**Comment by Anureng** [comment]
Created a pull request .
I don't see any break on Trade Page .

**Comment by dcts** [comment]
Fixed by #398
