### ISSUE TITLE
mobile responsive search suggestion overflow

### ISSUE THREAD

**Issue by SandipGyawali** [DeXter-on-Radix/website#393]
![image](https://github.com/DeXter-on-Radix/website/assets/66510112/ba56f038-d023-4a57-8eeb-a208fb7d48ad)

![image](https://github.com/DeXter-on-Radix/website/assets/66510112/f0f4133a-8aa7-4d00-9426-02709de57041)

search bar suggestion list overflow from it's maximum height.

**Comment by SandipGyawali** [comment]
@EvgeniiaVak i guess this issue has not be addressed previously right ?

**Comment by restylianos** [comment]
![Uploading Screenshot 2024-05-17 at 6.19.06 PM.png…]()
