### ISSUE TITLE
Setup Next.js to build static site (or switch off SSR)

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#4]
It would be cool to be able to simply host files without running a dedicated server for the frontend. Similar to pure frontend dApp architecture [described here](https://docs-babylon.radixdlt.com/main/getting-started-developers/dapp-frontend/building-a-pure-frontend.html)

**Comment by fliebenberg** [comment]
My understanding is that this will be the type of app we are building. We will not need any smart contract functionality for our app. It will simply interact with the existing alphadex smart contracts through the Radix wallet. The website wont be static though, as it will be receiving live exchange data from the alphadex sdk, which is getting data off the Radix ledger
.

**Comment by EvgeniiaVak** [comment]
I assumed next.js had some build-plugin or config for static sites, but it doesn't look like it, the closest thing I could find to what we need for the document reference is this - https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr

**Comment by RepServ** [comment]
It's the best path to take. Please what progress has been made so far?

**Comment by EvgeniiaVak** [comment]
@RepServ basically we are developing with this in mind, so it's kinda done. What's left (switching off the SSR) does not mean much logic change, but maybe some settings for deployment.

**Comment by RepServ** [comment]
Well done!
