### ISSUE TITLE
Rewards page claim rewards button shows as disabled but it's actually not

### ISSUE THREAD

**Issue by yuliaSharabi** [DeXter-on-Radix/website#401]
**Step to reproduce:**
Connect your wallet to the Rewards page, while you do not have any rewards.
Approve on the wallet app.

**Excpected:** None rewards appear on the webpage. The "claim ALL rewards" button is not clickable
**Actual:** :The button is grayed out but it's still clickable.
When I click the button it's initiated a trx on my wallet app.
![image](https://github.com/DeXter-on-Radix/website/assets/22341165/bc03fa77-6669-468e-aa8b-c9d41bfdd0e7)

**Comment by yuliaSharabi** [comment]
[Screencast from 2024-05-13 17-03-46.webm](https://github.com/DeXter-on-Radix/website/assets/22341165/76f18922-7cf3-4539-8946-a829d6e5a446)
You can see here that even there is no rewards to claim, the buttom is clickable and a request to wallet is initiated.

**Comment by dcts** [comment]
Good catch, that is definately not intended! And you can actually claim empty rewards, you pay TX fees but claim nothing. So basically just burning TX fees lol.

**Comment by dcts** [comment]
Fixed by #405 , closing.

**Comment by dcts** [comment]
reopening until #405 is merged :)
