### ISSUE TITLE
Typo in CONTRIBUTING.md: "without" incorrectly spelled as "wihtout"

### ISSUE THREAD

**Issue by mademoiselle-chantal** [DeXter-on-Radix/website#403]
## Description
There is a typo in the `CONTRIBUTING.md` file. The word "without" is incorrectly spelled as "wihtout".

## Location
The typo is found in the `CONTRIBUTING.md` file.

<img width="1085" alt="Screenshot 2024-05-14 at 08 17 01" src="https://github.com/DeXter-on-Radix/website/assets/120084609/d3948ea5-6ada-4fde-b2da-4dac2e617bcc">

**Comment by dcts** [comment]
Hey @mademoiselle-chantal , for typos like this feel free to directly create a PR with the fix.

**Comment by mademoiselle-chantal** [comment]
> Hey @mademoiselle-chantal , for typos like this feel free to directly create a PR with the fix.

Alright! I'm working on it now.

**Comment by dcts** [comment]
Fixed by #404
