### ISSUE TITLE
BUG: language selection is not persistend

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#415]
There seems to be something off with language selection cookie. Expected behavior is that language selection will be stored inside the cookie, so once selected you should not have to switch language again. 

# Expected Behavior:
- open dexteronradix.com/trade
- set language to PT
- open landing page -> language should be in PT
- open trade page -> language should still be in PT
- reload page -> language should still be in PT

# Actual Behavior:
This happens on my machine, not sure if this is reproducable. But in any case, its weird behavior I need to investigate. 
- on Brave: whenever I reload the page language selection seems to be reset to EN
- on Chrome: the language selection seems to always reset to PT on trade page, and always resets to EN on landing and trade page.

If you see this, please report if you can reproduce or not, I'm curious to see whether it affects only me.

**Comment by yuliaSharabi** [comment]
@dcts The 3 use cases on FF works well. 
On Chrome - any action when you switch to Trade/Reload will default it to EN, even if you choose SP.
