### ISSUE TITLE
Required Disclosures and Disclaimers (and other legal stuff)

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#43]
What disclosures and disclaimers do we need to have on our app?

**Comment by maelsar** [comment]
added a file terms.md

• This is the first iteration of the terms and privacy.
• This is meant to be the groundwork for more qualified contributors to add/remove
• View in markdown to be easier to read
• Sections in BOLD are areas which needs some extra feedback
• I took reference from: both are orderbooks dexs
https://exchange.idex.io/legal#privacy-policy
https://dydx.exchange/terms


[TERMS.md](https://github.com/DeXter-on-Radix/website/files/12236867/TERMS.md)

**Comment by fliebenberg** [comment]
Thanks @maelsar . Ill try to have a look at this over the weekend and provide feedback, if any needed. You could also maybe mention this in the telegram channel as there might be people there with some legal knowledge/experience.
