### ISSUE TITLE
Show resource addresses

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#432]
Currently there is no way for the user to determine the resource address of the traded tokens. When we allow permissionless listing on dexter as its currently the case we run into the potential scenario that a duplicate fake coin could be created and the user would have no way to verify the legitimacy of the coin by checking the resource address. 

We should add the resource address in the UI. I suggest to create an "Info" tab next to "PriceChart".

**Comment by dcts** [comment]
I suggest to show the following data inside the INFO tab:
- token 1 + token 2:
  - icon url
  - ressourcce address (including link to radix-dashboard
  - name
  - symbol
- information on the adex pair:
  - address: The on-ledger address of the pair component for the pair
  - rderReceiptAddress: The on-ledger resource address of the order receipt NFT for the pair
  - name: Name for the pair. Will usually be a combination of the symbols of the tokens in the pair. e.g. ADEX/XRD

**Comment by dcts** [comment]
The Design for this feature is now finished!

![image](https://github.com/user-attachments/assets/a1997641-912f-4522-852f-8cafec4fd390)

Figma File:
https://www.figma.com/design/Zjff03BX35fREatqzcWDS7/DeXter-UI?node-id=0-1&t=zvlr18AoVEWZQfqt-1

The file is full with designs, so its hard to find, but here a roadmap: 
(1) go to "Prototypes and tests"
(2) right unter voting app design you can find this design (see below). 
![image](https://github.com/user-attachments/assets/8659e8e8-b788-4cde-a855-4d210a4d6c8d)


# How to get the data from redux

The data for this is already available, you can get it by combining data from the rewardSlice and PairSelectoSlice. You can follow this logic:
```ts
// 1. get array of all pairs
const { pairsList } = useAppSelector((state) => state.rewardSlice);

// 2. get currenlty selected pair address
const selectedPairAddress = useAppSelector((state) => state.pairSelector.address);

// 3. get the relevant pairInfo
const pairInfo = pairsList.find((pairInfo) => pairInfo.address === selectedPairAddress);
const { name, address, orderReceiptAddress, token1, token2,  } = pairInfo;
```

**Comment by fliebenberg** [comment]
This would be a great addition. I would suggest we call the tab "Pair Info" rather than "Token Info" as indicated on the design.

**Comment by saidam90** [comment]
You can assign this to me 🤚🏼
