### ISSUE TITLE
Rewards Page Table Overlapped by Footer

### ISSUE THREAD

**Issue by Radstakes** [DeXter-on-Radix/website#454]
![image](https://github.com/DeXter-on-Radix/website/assets/83462165/12301a4e-5028-4b52-9317-e56a4fae0092)
Just noticed this issue when claiming the latest rewards.  If I zoom out to 67% it's fine, but anything more than that (I normally zoom to 80%), the table is clipped.

**Comment by dcts** [comment]
I could replicate this! Working on it.
