### ISSUE TITLE
Redux anti pattern spottet

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#458]
Based on @restylianos feedback, I just read some redux docs and found this section:
![image](https://github.com/DeXter-on-Radix/website/assets/44790691/9b3f7575-6c0d-43f4-b837-5adfbcc974d6)
(source: [redux docs](https://redux.js.org/tutorials/fundamentals/part-3-state-actions-reducers#reducers-and-immutable-updates))

We follow this antipattern in almost all of our slices and reducers, some examples:
- [OrderBookSlice (lines 161-165)](https://github.com/DeXter-on-Radix/website/blob/main/src/app/state/orderBookSlice.ts#L161-L165)
- [OrderInputSlice (lines 552-561](https://github.com/DeXter-on-Radix/website/blob/main/src/app/state/orderInputSlice.ts#L552-L561)
- [RadixSlice (lines 29-30)](https://github.com/DeXter-on-Radix/website/blob/main/src/app/state/radixSlice.ts#L29-L30)

For more context, I'll add a screenshot on what issues could arise using this antipattern and what pattern to use instead to avoid these:
![image](https://github.com/DeXter-on-Radix/website/assets/44790691/9ce5c476-a543-47bc-8fd9-0d862a0b22ce)

**Comment by EvgeniiaVak** [comment]
While this is true for pure redux, it's OK to assign like this with redux toolkit (inside slices) - https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#using-createslice

**Comment by dcts** [comment]
Closing as this is not a bug but a feature 😀
