### ISSUE TITLE
Add toggle to show all trades in Account Hisotry

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#484]
Currently, the Account Hisotry only shows trades that are related to the currently selected pair. We'd like to introduce a toggle on the top right corner of the AccountHistory component with the label "hide other pairs" which is turned on by default. The user should be able to unselect the toggle, which should then show all trades in all pairs. 

## **Design Mock**

<img width="1578" alt="Bildschirmfoto 2024-07-18 um 21 10 42" src="https://github.com/user-attachments/assets/b9e5c3a7-0f45-441e-af84-6d69a5112771">

**Design Figma File**

https://www.figma.com/design/Zjff03BX35fREatqzcWDS7/DeXter-UI?node-id=825-6498&t=gGYTb36pl7VTuLuV-1

**Comment by saidam90** [comment]
Could you assign me for this one?

**Comment by dcts** [comment]
We need to adapt the data fetching strategy to make this feature work. Given [this discussion on discord](https://discord.com/channels/1125689933735145503/1265098533355257906), I suggest the following strategy:

1. Create a new field in the [AccountHistoryState](https://github.com/DeXter-on-Radix/website/blob/044c41443def76677961c5b95da33664dcc0328c/src/app/state/accountHistorySlice.ts#L30) named `orderHistoryAllPairs: adex.orderReceipt[]`, which will hold all orderReceipt's for all pairs.

2. Create an additional [asyncThunk](https://github.com/DeXter-on-Radix/website/blob/044c41443def76677961c5b95da33664dcc0328c/src/app/state/accountHistorySlice.ts#L46) named `fetchAccountHistoryAllPairs`, that mimicks the `fetchAccountHistory` function, but asynchronously fetches orders for all pairs. This means we need to call `adex.getAccountOrders(account, pairAddress)` as many times as we have pairAddresses. You can get an array of all pairAddresses using 
```js
const state = thunkAPI.getState();
const pairAddresses = state.pairSelector.pairsList.map(pairInfo => pairInfo.address);
```
The orders should be aggregated into a single array of `adex.orderReceipt` and stored inside the state variable `orderHistoryAllPairs`.

3. The fetching of account history data should only be done when the user untoggles "hide other pairs". During that process there should be a loading indication. We probably want to keep track of the state of the toggle inside redux (maybe inside a bool `hide_other_pairs` which is `true` by default.

4. Currently we use a polling strategy to keep account history in sync, see code here:
https://github.com/DeXter-on-Radix/website/blob/044c41443def76677961c5b95da33664dcc0328c/src/app/trade/page.tsx#L45-L52
We should implement something similar, but I suggest having a longer timeframe (e.g. 2 mins):
```
  useEffect(() => {
    const intervalId = setInterval(() => {
      dispatch(fetchAccountHistoryAllPairs());
    }, 120000); // Dispatch every 2 mins (120 seconds)

    return () => clearInterval(intervalId); // Cleanup interval on component unmount
  }, [dispatch]);
```
