### ISSUE TITLE
Automated Liquidity

### ISSUE THREAD

**Issue by yuliaSharabi** [DeXter-on-Radix/website#487]
This would include:
Having the ability for the user to auto provide liquidity with a given parameters - pair, price.
Graphical representation of the liquidity.(different distributions - linear, extremes,mid distribution).

Based on the following [proposal](https://docs.google.com/spreadsheets/d/1cBV0zQzP3wGaTliD-iU-N7hQ4TfA2hxZG1FLH5f8ggU/edit?gid=0#gid=0).

**Comment by fliebenberg** [comment]
I have written a liquidity bot that does automated liquidity provision. It is quite simple and works best when it has a lot of liquidity relative to the order sizes it is placing. I could make the bot code publicly available (and probably still will), but I am thinking of rather creating some kind of a pooled instrument that people can use to provide liquidity for the bot. This will mean Dexter can offer liquidity provision opportunity that is similar to what you get on an AMM. The user can then add/withdraw liquidity whenever they want and it will help the bot be much more efficient in proving liquidity on Dexter.
I will need to flesh out the idea further still and then find time to build the components required. But thought I'd mention it already to hear other views.

**Comment by dcts** [comment]
@yuliaSharabi Closing this issue due to ambiguity. The trading bot and batch order tool are separate projects (I handle the batch order tool, Fred works on the bot). I've created two new issues to clarify and separate these tasks, see:
#538 and #539
