### ISSUE TITLE
Add stats widget on landing page

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#494]
# Problem

DeXter visitors currently lack visibility into the exchange's scale. Key metrics like daily/weekly volume and the number of listed tokens are typically shown to provide this information.

**Examples / Inspiration from Binance and Uniswap**:
<img width="677" alt="Bildschirmfoto 2024-07-25 um 00 21 46" src="https://github.com/user-attachments/assets/f9d140ea-a885-436b-b39e-b2df69c160eb">

# Your Task

- [ ] Collaborate with our designer Mauro (@m_jota_ on discord) to decide on the top 3 metrics to display. List of available metrics (feel free to brainstorm other metrics as well):
  - Number of pairs listed
  - Total trade volume (in XRD or USD)
  - Trade volume in the last 24 hours
  - Trade volume in the last 7d (available soon)
  - Average weekly trade volume since inception (in XRD and USD)
- [ ] Implement the agreed-upon design once mocks are ready.

# Data Sources

## Redux state

Access 24-hour (and soon 7-day) trade volume for each pair from the `rewardSlice`. The `pairsList` array contains [adex.PairInfo](https://socket.dev/npm/package/alphadex-sdk-js#pairinfo-classtype) objects. Example:

```js
  const { pairsList } = useAppSelector((state) => state.rewardSlice);
  // Get a random pairInfo
  const pairInfo = pairsList[0]; // e.g. DEXTR/XRD
  console.log(pairInfo.quantity24h);  // Volume in token1, e.g. in DEXTR
  console.log(pairInfo.value24h);  // Volume in token2, e.g. in XRD
```

## Public Google Sheet

Weekly trade volumes are tracked in this [Google Sheet](https://docs.google.com/spreadsheets/d/1t0QVTUzNTACNmX6GFG-wFOqHw1dqpQHcTbAufrGn6y8/edit?usp=sharing), specifically in the "Trade Volume Total" sheet.
<img width="382" alt="Bildschirmfoto 2024-07-25 um 00 12 04" src="https://github.com/user-attachments/assets/dcfda6fc-631d-4606-bd68-d98318950c8f">

Example code for fetching data from Google Sheets can be found [here](https://github.com/DeXter-on-Radix/website/blob/044c41443def76677961c5b95da33664dcc0328c/src/app/kpis/kpis-utils.ts#L33-L42).

**Comment by SiegfriedBz** [comment]
You can assign this one to me
