### ISSUE TITLE
Export orders as CSV

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#495]
## Problem

Currently there is no way of exporting orders (open or history) from dexter. 

## Your Task

I suggest to add a small secondary button "export as csv" below all tables, that allow users to export the data inside the table as CSV. 

<img width="880" alt="Bildschirmfoto 2024-07-25 um 00 44 45" src="https://github.com/user-attachments/assets/ff97eb33-13ea-467b-a8c2-a8e781e16b8f">

## Data

The data of all orders can be retrieved from our redux state, especially from `accountHistory` -> `orderHistory`.

```js
const { orderHistory } = useAppSelector((state) => state.accountHistory);
console.log({ orderHistory });
```

**Comment by nipun-sachintha** [comment]
For testing how we can add orders. Is there any guide relevant to adding active orders and get history

**Comment by dcts** [comment]
Hi @nipun-sachintha 

Yes we have this guide which explains how to setup a wallet and testnet:
https://dexter-on-radix.gitbook.io/dexter/stokenet-testing/setup

If you run into any issues please let me know!

**Comment by dcts** [comment]
@nipun-sachintha Just a side note, once you have the setup and test orders ready, please work on another issue as there is already a PR for this one ><

**Comment by dcts** [comment]
Already implemented!
