### ISSUE TITLE
Investigate what data we will need from the API

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#5]
This is purely under the hood investigation and thus is not blocked by any design specification work. We need to have a look into AlphaDEX API data and see what methods we can use. 

AlphaDEX spec is here: https://www.postman.com/alphadex/workspace/public-workspace/overview
main site: https://alphadex.net/

**Comment by fliebenberg** [comment]
We will probably get away with using the AlphaDEX SDK for 99% of what we need to do on Dexter. It can provide a live data feed for all the data needed and can facilitate the submission and cancellation of orders. There are existing tutorials on how to integrate the SDK with either a Svelte or React app that you can go through for practice here: https://medium.com/alphadex-xrd/alphadex-tutorials-2fb17ea04dbb. You can also find detailed documentation for the SDK on its npm page: https://www.npmjs.com/package/alphadex-sdk-js
