### ISSUE TITLE
Create 404 page

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#503]
# Problem

When users encounter a dead link, they currently see an unprofessional 404 error page. This can negatively impact user experience and our brand's image.

![404-current](https://github.com/user-attachments/assets/94cf5e0d-693c-4dcf-a602-26c9072123b3)

# Your task

- Collaborate with our designer Mauro (`m_jota_` on discord) to create a mockup for a 404 page that aligns with DeXter's branding.
- Implement the new 404 page design.
- Ensure all dead links display the updated 404 page (e.g., dexteronradix.com/asd).

**Comment by SiegfriedBz** [comment]
You can assign me this one
