### ISSUE TITLE
Animate Landing Page Lights

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#504]
# Problem

The landing page looks visually appealing but feels static. Adding subtle animations can make it more dynamic, engaging, and lively.

# Your Task

Animate the two light effects (green and blue) on the landing page to make them slightly move, enhancing the overall user experience.
![image](https://github.com/user-attachments/assets/a9fb93a6-acbc-4cdc-91f4-dffb9253e6ed)

**Reference Animation:**  
Here’s an example of light movement generated by ChatGPT: [Light Animation Example](https://codepen.io/dcts-the-decoder/pen/pomJKRX).

**Suggestions:**
- Consider making the lights move in opposite directions for added effect.
- Feel free to experiment with other animation ideas to find the most visually appealing solution.
- Feel free to share your suggestions on our Discord server (UX/UI channel) or contact Mauro, our designer, on Discord (@m_jota_).

# Happy creative coding!

**Comment by SiegfriedBz** [comment]
Are you opened to the aceternity library ? 
https://ui.aceternity.com/components/background-gradient-animation

If yes I would be happy to tackle this issue with it, and if no I will be happy to find another way to tackle it :)

**Comment by saidam90** [comment]
🤚🏼

**Comment by dcts** [comment]
@SiegfriedBz I know you tested implementing this too, are you still working on it or can I assign it to @saidam90 ?

**Comment by SiegfriedBz** [comment]
@dcts  I leave it to @saidam90
