### ISSUE TITLE
Price calculation when insufficent funds in wallet

### ISSUE THREAD

**Issue by yuliaSharabi** [DeXter-on-Radix/website#513]
When you put the token amount that is bigger then the amount you have in the connected wallet the token2 calculation +fees are wrong.

WHEN SELL+MARKET it's not hapenning:
![image](https://github.com/user-attachments/assets/2d9e3b74-62c5-44af-9e84-b7ef0c849486)

Need to check all combinations once fixed!
![5852898152582072087](https://github.com/user-attachments/assets/aa333ba7-2c0e-4b5d-8594-ab1e5244abc5)

**Comment by fliebenberg** [comment]
So instead of showing the result that will be possible with the amount in the user's wallet, we should rather show the result as if they have the amount entered. We can still not allow the order to be submitted by making the submit button inactive.

**Comment by dcts** [comment]
@yuliaSharabi Just as a side note: I don't think it works on SELL MARKET either. If you look at your inputs, its 4000 DEXTR entered, but the shown amount is 304 XRD (which is too low given the price is approximately 0.8). 

So I assume the 304 XRD shown is the amout that was calculated using 400 DEXTR (as that balance is sufficient). But adding the additional 0 did not retrigger the calculations. You can doublecheck by keep adding zeros.
