### ISSUE TITLE
Fetch all users script

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#517]
# Problem

Currently, we lack information on the number of unique users and their activity on DeXter. Although all data is publicly available on the ledger, it needs to be aggregated and analyzed. We should also display this data on the landing page in the stats widget (instead of showing an aggregated follower count).

# Your Task

Implement a script using the Alphadex JS API to fetch all orders for all pairs. Store unique addresses in a hashmap and count the number of orders per address.

# Impelementation hints

- IMO its best to create a standalone script inside `scripts/fetchUsers.js`. You can either use JS or TS, whatever you prefer.
- Use the [alphadex JS API](https://socket.dev/npm/package/alphadex-sdk-js). 
- First you will need to get an array of all [PairInfo](https://socket.dev/npm/package/alphadex-sdk-js#pairinfo-classtype) objects.
- The you will need to find out `lastOrderId` and `address` of the pair, which are needed to construct the inputs for [`getPairOrders()`](https://socket.dev/npm/package/alphadex-sdk-js#getpairorders-async-function-back-to-functions-list).
- I am not sure how to get `lastOrderId`, see [discussion on discord](https://discord.com/channels/1125689933735145503/1267244455153504291/1267865097846390880)
- I am not sure what the quota is for the API (how many requests we can trigger per minute), see [discussion on discord](https://discord.com/channels/1125689933735145503/1267244455153504291/1267873267402932225)

### Code snippet (did not test, please modify as needed)

```js
// import all the sdk functions and variables as adex
import * as adex from "alphadex-sdk-js";
...
// run the sdk init function to establish a live connection with the exchange
adex.init();

// use the variables with the live data in your program/app
let adexState = adex.clientState;

// get all PairInfo
const pairsList = adexState.pairsList;

// Exampele for a single pair
const pairInfo = pairsList[0];
const pairAddress = pairInfo.address;
const pairLastOrderId = 10; // TODO: find out how to get this data
const allOrderIds = [...Array(pairLastOrderId).keys()]; // => [1,2,3,...,pariLastOrderId]

// fetch all orders for that pair
const result await adex.getPairOrders(pairAddress, allOrderIds);
console.log(`first 5 orders or pair ${pairAddress}:`);
console.log(result);

// TODO: For each order, find out the wallet address of the creator, and store inside a hashmap/object
const users = {};
// example
users[radixWalletAddress] = users[radixWalletAddress] ? users[radixWalletAddress]+1 : 1;

// TODO: iterate over all pairs

// TODO: ideally the script should show logs (progress bar)

// TODO: I suggest to make the script syncronous at fist
// and move to async later if it takes too long. 
// making it syncronous at the beginning will make sure
// we don't run into API quota issues (hopefully)
```

**Comment by SiegfriedBz** [comment]
Here are some updates I made to handle fetching user orders and counting wallet addresses. Below is a rundown of what I tried, including some notes and observations:

scripts/fetchUsers.js
```javascript
// import * as adex from "alphadex-sdk-js";

const fetchUsers = async () => {
  try {
    // fetch all pairs
    const allPairsResponse = await fetch(
      "https://api.alphadex.net/v0/alphadex/pairs",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    if (!allPairsResponse.ok) {
      throw new Error("fetchUsers -> Error while fetching pairs");
    }

    const allPairsData = await allPairsResponse.json();
    const pairsList = allPairsData?.pairs || [];

    // Aggregate all pairs info
    const pairsInfo = pairsList.map((pair) => ({
      pairAddress: pair.address,
      lastOrderId: pair.lastOrderId,
    }));

    // test 1 - establish a live connection with the exchange
    // await adex.init();
    // const allOrders = await adex.getPairOrders(pairAddress, orderIds);
    // => Note: adex.getPairOrders(pairAddress, orderIds) makes a POST request to
    // "https://apitest.alphadex.net/v0/pair/orders";
    // ===> returns a 400 with "Unrecognized pair address" so I assume this pair is not referenced in "apitest", while we fetch all pairs from "api"

    // test 2 - manual POST TO "https://api.alphadex.net/v0/pair/orders"
    const fetchLastOrderByPair = async (pairAddress, orderIds) => {
      try {
        const response = await fetch(
          "https://api.alphadex.net/v0/pair/orders",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify({ pairAddress, orderIds }),
          }
        );

        if (!response.ok) {
          throw new Error(
            "fetchUsers -> Error while fetching last order by pair"
          );
        }

        const data = await response.json();
        return data;
      } catch (error) {
        console.error("fetchLastOrderByPair -> error", error);
        return { orders: [] };
      }
    };

    // fetch all (last) order for all pairs
    const allOrders = await Promise.all(
      pairsInfo.map((pair) => {
        const { pairAddress, lastOrderId } = pair;
        return fetchLastOrderByPair(pairAddress, [lastOrderId]);
      })
    );

    // Process orders to count wallet addresses
    const usersFreqCounter = allOrders.reduce((acc, curr) => {
      if (!curr?.orders?.[0]) return acc;

      const order = curr.orders[0]; // only 1 order is fetched with fetchLastOrderByPair

      const radixWalletAddress = order?.settlementAccount; // settlementAccount is the only key I found in the order object, matching an account address

      if (!radixWalletAddress) return acc;

      return {
        ...acc,
        [radixWalletAddress]: (acc[radixWalletAddress] || 0) + 1,
      };
    }, {});

    return usersFreqCounter;
  } catch (error) {
    console.error("fetchUsers -> error", error);
  }
};

export default fetchUsers;


```

**Comment by fliebenberg** [comment]
const allOrders = await Promise.all(
      pairsInfo.map((pair) => {
        const { pairAddress, lastOrderId } = pair;
        return fetchLastOrderByPair(pairAddress, [lastOrderId]);
      })
    );
    
    In the above code you probably want to call fetchLastOrderByPair with more than just lastOrderId in the array. You need to specify the orderId of each order you want to fetch in the array (and it is limited to max 100), so you might need to create an array of orderIds to send to fetchLastOrderByPair function.
E.g.
// create order id list for pair
orderIdsList: number[] = [];
for (const orderId: number = 1; orderId <= lastOrderId; orderId ++) {
orderIdList.push(orderId);

// fetch order details in batches of 99
let allPairOrders = [];
let batchSize = 99;
let index = 0;
while (index < orderIdList.length) {
  let batchIds = orderIdList.slice(index, index+ batchSize);
  let batchOrders = fetchLastOrderByPair(pairAddress, batchIds);
  allPairOrders = [...allPairOrders, ...batchOrders];
  index = index + batchSize;
}

**Comment by SiegfriedBz** [comment]
Thanks @fliebenberg ! I just discussed it with @dcts. There was something I misunderstood.. all good, I will set a range from 1 to lastOrderId and fetch them all

**Comment by SiegfriedBz** [comment]
updated in PR #521
