### ISSUE TITLE
Connector extension/wallet/rdt to v0.3

### ISSUE THREAD

**Issue by SmashingBumpkin** [DeXter-on-Radix/website#53]
I've just updated everything to v0.3 and it no longer connects. The docs aren't great on this right now, and there's no way back to v0.2 on the wallet, so be warned.

**Comment by SmashingBumpkin** [comment]
Definitely partly due to the dapp not being deployed on networkID 13

**Comment by SmashingBumpkin** [comment]
Latest commit to order-button-on-v0.3 has got things (on the surface level) working, though there is a lot of cleanup to be done on the rdt stuff. Currently I think I'm pretty limited in what I can do on the button until alphadex is running on network instance 13 @fliebenberg

**Comment by fliebenberg** [comment]
I am working fulltime to get AlphaDEX onto RCNet v2 (network id 13) as soon as possible. I already have an AlphaDEX component deployed on the network (that took some trial and error as there are still some bugs the team is working on) and have managed to start submitting transactions to the deployed smart contract. Now just working on making sure the AlphaDEX API and SDK can work with the new network. Hoping to have something to connect to by tomorrow end of day, but not making any promises. :-)
