### ISSUE TITLE
Sorting of account history not working

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#536]
I experience a weird bug, where the ordering in the account history is not correctly working. The orders should be ordered by timeSubmitted, yet they appear to not be properly sorted:

(See below the ordering is not correct)
![Bildschirmfoto vom 2024-08-04 02-35-39](https://github.com/user-attachments/assets/69eade0d-e12f-40d0-8b34-716d4c3e6dba)

**Comment by yuliaSharabi** [comment]
It looks like it's ordered by Time_completed. Shoudn't it be like that? Also, maybe cancelled order should not appear first in order?

**Comment by yuliaSharabi** [comment]
@dcts You missed my comment, can you relate please?

**Comment by dcts** [comment]
Yes odering is indeed using timeCompleted, so all good. 

About cancelled orders, if they took place most recently I believe they could appear on top. But I agree it looks odd. Not sure about that but I dont think its a high priority task currently. The account history tables will need a major redesign at some point, but we havent had time to implement it yet.
