### ISSUE TITLE
When scrolled down a bit and waiting the page jumps to top again

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#54]
For easier testing can use data from binance, it updates more often.

**Comment by SmashingBumpkin** [comment]
This isn't happening consistently on chrome/win11. I did notice a jump to the top once, but I'm not sure it was the update to the chart that caused it. I can watch price change and new candles appear and the page behaves normally.

**Comment by EvgeniiaVak** [comment]
yeah, maybe it's not the price chart, I have not investigated yet, just noticed the jumps

**Comment by maelsar** [comment]
not sure if this helps but I noticed it jumps up when you scroll down just immediately after you reload page.  I noticed the jump happens when AlphaDEX pairs list starts to render/populate.

**Comment by EvgeniiaVak** [comment]
I think this one was fixed by #73
