### ISSUE TITLE
Navbar menu on mobile doesnt use translations

### ISSUE THREAD

**Issue by dcts** [DeXter-on-Radix/website#555]
Theres 2 issues with the navbar menu on mobile:
1. The menu items are not capitalized
2. When switching to portugiese, the text doesnt change. 

![Screenshot_2024-08-11-21-04-42-860_com brave browser](https://github.com/user-attachments/assets/dea85b41-729c-4f73-aab5-018e3e98a9c5)

**Comment by Pratham-Gaikwad** [comment]
I’m interested in working on this issue. Could I take this on?

**Comment by dcts** [comment]
> I’m interested in working on this issue. Could I take this on?

Hi @Pratham-Gaikwad ! Thank you for your interest in working on this! I assigned you.

**Comment by dcts** [comment]
fixed in #557
