### ISSUE TITLE
Many digits numbers shorthand

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#57]
The poll of how to write the huge and tiny numbers in the order-book table resulted in K for 1000s and M for 1000000s - https://t.me/dexter_discussion/4096

There might be some problems with that because it does not solve the very tiny numbers (or might be unintuitive if we use small letters). 

Need to research what numbers there will be in the table, test how they look in the UI, see if we can have any problems and maybe implement another solution.

**Comment by fliebenberg** [comment]
Closing this issue as it has been resolved by the new displayAmount function. We now only need to decide how many digits we want to display in different places on the DeXter UI.

**Comment by EvgeniiaVak** [comment]
@fliebenberg you can write on top of your PRs descriptions that they fix some issue, e.g.:
```
fixes #57
```
and when a PR is merged it will close the issue automatically (and there will be a link between the issue and a PR)
