### ISSUE TITLE
App Crashes when I click on DFP2-XRD pair "Recent Trades" tab

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#587]
The app completely crashes when I click on the "Recent Trades" tab when in the DFP2-XRD pair. The console log says there is a division by 0 error.

**Comment by yuliaSharabi** [comment]
I was able to reproduce it as well on Production but not on stokenet we don't have the pair and the other pairs aren't crushing the app.
I suspect where it it's coming from, but can we load the pair to testnet in order to test it?
@fliebenberg @dcts

**Comment by fliebenberg** [comment]
What do you think is causing the problem? We cannot create exactly the same pair as the tokens are not on stokenet. But we can try to replicate the problem with a new pair on stokenet. So if you can describe what you want us to replicate I can try to see if I can set up a pair with those conditions.

**Comment by yuliaSharabi** [comment]
Fix is in:
https://github.com/DeXter-on-Radix/website/pull/588

My investigation is as follows:
In DFP2-XRD pair, last order has 0 size, this assign to trade.token1Amount the value 0. Which makes the division by zero occur and crush while you choose recent Trades view tab. 
![image](https://github.com/user-attachments/assets/79247e57-559c-433d-9b92-a0b06760b763)

**Comment by yuliaSharabi** [comment]
Issue was merged.
