### ISSUE TITLE
Mismatch on Trades text in pair Xraw/xrd - 2 BUY orders but appears also "No Trades have occured yet"

### ISSUE THREAD

**Issue by yuliaSharabi** [DeXter-on-Radix/website#589]
On the Trades book on the left it appears "No trades have occurred yet" but there is 2 BUY orders at the moment.
![image](https://github.com/user-attachments/assets/8eefb3e5-37b3-4c0d-963e-33514062a253)

**Comment by yuliaSharabi** [comment]
@dcts @fliebenberg Any thoughts on the matter?

**Comment by fliebenberg** [comment]
This is probably correct. It means even though there are 2 buy orders available, no one has wanted to sell at those prices. So there have been no trades in the pair yet, even though there are open orders.

**Comment by yuliaSharabi** [comment]
Then why the behaviour is inconsisten over other pairs?
@fliebenberg 
Example - DFP2/XRD:
No Buy, Just Sell, but the "No trades occured yet" text is not appearing in this case.
![image](https://github.com/user-attachments/assets/8fee4c3e-ba58-483e-a1a7-6b3c9050336b)

DGC/XRD pair: opposite example, Sell, no Buy. No Trades text isn't there too.
![image](https://github.com/user-attachments/assets/82047fc5-497e-47c9-a0a3-48fd85dbe492)

**Comment by dcts** [comment]
I dont see inconcistency. Theres the following scenarios:
- did trades happen in the past -> yes/no. If "no" we show "no trades have occured yet"
- are there buy orders on the orderbook -> if "no" we show "no open buy orders"
- are there sell orders on the orderbook -> if "no" we show "no open sell orders". 

All 3 things are independant of each other. So you could have all 3 messages, or only 2 or 1 or none of them.

**Comment by yuliaSharabi** [comment]
If both DFP2/XRD and  Xraw/xrd has sell orders. Why on one of them there is Trades and on the other there isn't?

Maybe I do not understand what you consider a Trade. But if there is someone selling then there should be also a buy order in order for the text of the trades not to appear?
I am confused.

**Comment by dcts** [comment]
> If both DFP2/XRD and Xraw/xrd has sell orders. Why on one of them there is Trades and on the other there isn't?

So there is a difference between orders and trades. Orders can be open if they are limit orders. So if there are orders, it could still mean that no trades happened on this pair so far. 

> Maybe I do not understand what you consider a Trade. But if there is someone selling then there should be also a buy order in order for the text of the trades not to appear? I am confused.

Yes as you said correctly, if a trade happened, there will always be orders. But if there are orders, its not given that there were trades made, as the order could simply be put on the orderbook with no counterparty.

I am closing this issues, as I don't see any bug here. Please re-open if you think otherwise or DM me for further explenation.
