### ISSUE TITLE
Cancel orders functionality not working correctly

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#592]
When I select an order to cancel in one pair, it shows "Cancel 1 Order" in red at the top of the column.
![image](https://github.com/user-attachments/assets/a22ea31c-57fd-4a23-8b75-a084dfce9a82)
When I then navigate to another pair, the red "Cancel 1 Order" is still displayed although I am now in a different pair with different open orders displayed - none of which are selected. If I now select an order here as well it will show "Cancel 2 orders" even though I am only seeing one order selected for the pair.
If I now navigate back to pair 1, it still shows "Cancel 2 orders" but it now shows no orders selected, not even the one I had selected previously. When I select that order again, it shows as selected but does not increase the count again.

I think we should make it that selected orders are reset every time the user changes pairs. So batch cancel should only work for one pair. In fact it will only work for one pair as cancel tx needs to specify a specific pair component.

**Comment by yuliaSharabi** [comment]
Does it works same way if the toggle of "hide other pairs" is on?

**Comment by dcts** [comment]
Just an info until this is fixed: You can always hard refresh the page on the pair you are currently on, that should resolve it.
