### ISSUE TITLE
Website not working for several people

### ISSUE THREAD

**Issue by fliebenberg** [DeXter-on-Radix/website#612]
From logs it looks like the website is constantly starting and breaking a connection with the AlphaDEX api/sdk.

**Comment by nguvictor** [comment]
From a quick glance it appears to be a potential circular redirect between api2 and api on alphadex
![image](https://github.com/user-attachments/assets/e0d04361-76be-45ac-804c-b4607856fa29)

**Comment by nguvictor** [comment]
Looks like it might be a redirect loop due to a certificate error with api.alphadex.net:
![image](https://github.com/user-attachments/assets/ecacb175-2b77-4e3f-953b-fbb3533bce33)
