### ISSUE TITLE
Unknown dApp

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#63]
Relevant docs: https://docs-babylon.radixdlt.com/main/getting-started-developers/dapp-frontend/dapp-definition-setup.html

- [x] #36 
- [ ] add metadata at https://rcnet-v2-dashboard.radixdlt.com/dapp-metadata
- [ ] add `.well-known/radix.json` (docs [here](https://docs-babylon.radixdlt.com/main/standards/metadata-for-verification.html#_declaration_and_handling_of_claimed_websites))

----

When connecting DeXter page to the wallet, on the phone is shows up as Unknown dApp.

![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/3275ae95-8059-4c3e-902b-71315a214442)

![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/896e8465-9553-48cb-a6eb-d271596b4cde)

**Comment by Radstakes** [comment]
Is this where the dapp definition will come into play?  I was just reading about this yesterday, but I presume it's where this metadata will be pulled from: [https://docs-babylon.radixdlt.com/main/getting-started-developers/dapp-frontend/dapp-definition-setup.html](url)

**Comment by EvgeniiaVak** [comment]
> Is this where the dapp definition will come into play? I was just reading about this yesterday, but I presume it's where this metadata will be pulled from: [https://docs-babylon.radixdlt.com/main/getting-started-developers/dapp-frontend/dapp-definition-setup.html](url)

this url redirects me to: https://github.com/DeXter-on-Radix/website/issues/url

**Comment by EvgeniiaVak** [comment]
Interesting, "dApp Definition Account"... We probably need a discussion somewhere on who should have access to this.
@Radstakes am I correct in understanding that we will be able to set it up only after official deployment?.. Or do we just need to prove we own a domain?
For tesnet we probably need to connect the testnet deployment, which will probably be on github or vercel, and when we go live well that's #8

**Comment by Radstakes** [comment]
Yep, but as it's just another account there's no reason why this couldn't be a multi-sig utilising a number of badges. 

> am I correct in understanding that we will be able to set it up only after official deployment?

Yes - that's my understanding too, but the details on dapp definition are a bit sparse at present. I will ask the team in Discord about this.

**Comment by Radstakes** [comment]
Update - it looks like that functionality is available already, we can set up the Dapp Definition in the RCNet dashboard here: [V2 Dashboard](https://rcnet-v2-dashboard.radixdlt.com/dapp-metadata)

It then has to be configured, as described here in the docs:

"When you set up the [Radix dApp Toolkit](https://docs-babylon.radixdlt.com/main/frontend/radix-dapp-toolkit.html) in your dApp frontend website, you’ll configure it with the dApp Definition address that you just created, and it will be sent to the Radix Wallet whenever a user connects or receives a transaction from your dApp. The Wallet will then look up that dApp Definition address on the Radix Network, pull the latest metadata, and show it to the user. When a user logins to your dApp, an entry in the wallet’s preferences for your dApp will appear too."

For now, I'd suggest @EvgeniiaVak controls the dapp definition, and at mainnet we configure the access to it using multiple badges.

**Comment by EvgeniiaVak** [comment]
https://rcnet-v2-dashboard.radixdlt.com/ does not recognize the new radix extension -> I'm using:
https://rcnet-v3-dashboard.radixdlt.com/

**Comment by EvgeniiaVak** [comment]
Ok will be able to add and update the linked websites when we have something deployed:

<img width="1468" alt="Screenshot 2023-08-13 at 12 11 57" src="https://github.com/DeXter-on-Radix/website/assets/27793901/3c816073-f02e-47ad-9d5d-51ae35e974de">

But while developing locally I guess we are bound to see unnamed dApp, because adding localhost:3000 does not make sense (people are developing not only DeXter app locally).

Our name is probably "DeXter", what about description? Maybe something form tg, I've seen a discussion there somewhere about a short description. @Radstakes @fliebenberg @ArthurQuantize

**Comment by Radstakes** [comment]
I think we need to think about getting a web2 domain for the app.  Even if we do host on IPFS or some other web3 solution we'll need an easy way of routing to the site.  I'll ask in the TG if anyone has any preferences.  Personally I like dexteronradix.com

For the description, I would suggest we just go for something like "The first order book exchange built entirely by the Radix community" or "the first community-built order book DEX on Radix".  The latter is the description used for the DEXTR token so we could keep it consistent with that.  There was some discussion in the TG, but that was more related to a tagline for the mascot, like "DeXter - Trade & Earn".

**Comment by fliebenberg** [comment]
Agree, that we need a web2 domain. we might use it in the beginning for hosting the site, but later might just route from that address to some other web3 type hosting solution. Happy with dexteronradix.com.
For the description, I think I would leave out the "first" as it makes it sound like there are others. But I suggest we have this discussion on the telegram channel.

**Comment by Radstakes** [comment]
So as I understand it, there is a 2 way linking between the website and the dapp definition.  The dapp definition sets the domain, and the domain must also set the dapp definition.  There are some more details on this here: [Metadata for Verification](https://docs-babylon.radixdlt.com/main/standards/metadata-for-verification.html#_declaration_and_handling_of_claimed_websites)

But what you are saying is true, anyone could set the metadata name to "DeXter", but I guess they would also need the right dapp definition, which would need to be linked to the right components on ledger, otherwise the wallet will flag "this is called DeXter, but the linked components are not as expected for this dapp definition"?  There is no guarantee that you're looking at the right DeXter of course, which incidentally is a feature we're building for XRD Domains, whereby we grant domains trust scores based on interaction with other accounts and a nexus (a bit like how LinkedIn connections work).

**Comment by fliebenberg** [comment]
Where are we on this issue? We should be able to create our dApp definition account already and link back to it from our website/app. Just checking if this has been done?

**Comment by EvgeniiaVak** [comment]
After the latest radix testnet update it's back to Unknown dApp and I lost the app definition (there was no option to resurrect it - https://discord.com/channels/417762285172555786/1018955196786823188/1151053527897096202 ). @fliebenberg do you want to create another one?

**Comment by SmashingBumpkin** [comment]
> So as I understand it, there is a 2 way linking between the website and the dapp definition. The dapp definition sets the domain, and the domain must also set the dapp definition. There are some more details on this here: [Metadata for Verification](https://docs-babylon.radixdlt.com/main/standards/metadata-for-verification.html#_declaration_and_handling_of_claimed_websites)

This is my understanding too, so we would need to setup "https://www.dexteronradix.com" in the dapp definition, and also add the dapp definition address to _every_ url/.well-known/radix.json/ we use. So if we have a web2 domain and web3 domain, both need to have the json setup.

As far as I can tell there's no way for us to add metadata saying that dexter only interacts with the alphadex package (at least, doing so requires the alphadex badge's approval)

**Comment by fliebenberg** [comment]
Yes, we need to set up a new dapp definition account for DeXter. When DeXter interacts with AlphaDEX (e.g. submitting a trade), the wallet should show both DeXter and Alphadex as apps. I have not set up a dapp definition for AlphaDEX on the latest testnet which is why it is not showing yet. I am building a few "admin" tools for AlphaDEX and want to wait to build a metadata editor to setup the dapp account. Hopefully I get to that this weekend still.
