### ISSUE TITLE
Decide what to use: `.` or `,` in numbers and test input fields

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#76]

**Comment by fliebenberg** [comment]
I suggest we read the current Locale number format and get the decimal and thousands separator from there and store them as variables to be used in displayAmount.

**Comment by fliebenberg** [comment]
OK, we have decided to not implement the locale specific separators for the MVP, so I suggest we just go for "." for decimal separator and " " for thousands separator. Any alternative suggestions?
BTW, these are the defaults in the displayAmount function at the moment.
