### ISSUE TITLE
A toast with transaction result

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#77]
When a transaction finishes with an error or success we could show this information somewhere on the page, maybe in a toast message for a few seconds.

- [ ] discuss with the team, especially designers [in figma](https://www.figma.com/file/P7pfzKwJ4G6ClapXfl61D3/Dexter-UI?type=design&node-id=352-14130&mode=design&t=S2s7zEaLUK5GmJU2-0)
- [ ] implement using daisyui
- [ ] add tests

**Comment by steferr** [comment]
@EvgeniiaVak Please check this page, it should contain what you need
https://www.figma.com/file/7ZTe3xNFJykxsJtBKi0tYI/Dexter-DS-BUG-SOLVED?type=design&node-id=133-2508&mode=design

**Comment by dcts** [comment]
> @EvgeniiaVak Please check this page, it should contain what you need https://www.figma.com/file/7ZTe3xNFJykxsJtBKi0tYI/Dexter-DS-BUG-SOLVED?type=design&node-id=133-2508&mode=design

The document is access restricted, could you make it public?

**Comment by dcts** [comment]
Already implemented in #323. Closing.
