### ISSUE TITLE
Showing more information before submitting transaction

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#78]
When getting a quote from AlphaDEX we get useful for user information that is [currently shown in a description field](https://github.com/DeXter-on-Radix/website/blob/f588c939defd7a692675a6229a660733987d2b02/src/app/components/OrderInput.tsx#L325) but we don't have it UI in figma

![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/f9fb0199-6df1-4f00-83f3-74b727e28469)

**Comment by yuliaSharabi** [comment]
Merged. 
Closing
