### ISSUE TITLE
Decide where to host

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#8]
We need to place somewhere our app for people to be able to reach it. Even during the development, I think it will be great to have it, so that not only coders can interact with it and give feedback in telegram. Options:

1. (for development stage only) GitHub or [vercel](https://vercel.com/) (these are old web2 solutions, but during the development, I think it'll be good to have one - they have freemium easy to setup ci/cd pipeline (with next.js vercel is easier than github for personal accounts, I don't know about ogs yet))
2. [flux](https://runonflux.io/)
3. [fleek](https://fleek.xyz/)

**Comment by timanrebel** [comment]
Can I throw in Cloudflare as an option as well? Their Pages set up works really well for frontend-only apps and afaik it's completely free for all basic features. Also supports Next.js

Astrolescent and Defiplaza fully run on Cloudflare. We do have a paid plan for some more advanced features, but we don't spend more than 20 to 40 USD a month on it in total (Mostly because at Astrolescent the algorithm runs on Cloudflare workers and gets called around 500k times a day)

**Comment by fliebenberg** [comment]
We need to pick up this issue now that we are getting closer to MVP release. We will need to host the MVP somewhere for the community to interact with it. Server's etc are not my field of expertise, but I just wanted to get this conversation going again.

**Comment by Radstakes** [comment]
I like the idea of CloudFlare that TIman suggested, perhaps worth a look if the free plan gives us what we need initially.  [CloudFlare Plans](https://www.cloudflare.com/en-gb/plans/). Do we want to consider a decentralised option, like IPFS from launch, or maybe for the MVP we just stick to web2 servers?

**Comment by Radstakes** [comment]
Also this just popped un in the Runs on Radix Discord channel.  As much as I don't like AWS, could also be an option...
![image](https://github.com/DeXter-on-Radix/website/assets/83462165/73fbf38d-e28a-4cf6-ba65-eca3cc97efb7)

**Comment by EvgeniiaVak** [comment]
I would go with the easiest option for testnet deployment. We don't even need a pretty domain for that. And I think it should be alive and separate from the live deployment:
1. deploy the test version somewhere that is cheap and easy to set up (I know how to do it on vercel and github, aws will probably also be easy), this version works with testnet AlphaDEX and will continue to work with testnet only, I would vote for this version to be deployed even right now, or after fixing known bugs (even though we don't have the layout yet, the functionality is there), we may need to hide it from the search engines #36 
2. wire up the automated updates, so that when we have something merged to main - our community can try it out
3. do some research on where to really host when we go to production (I vote for something closer to web3)

**Comment by Radstakes** [comment]
I agree - getting the test version up with automated updates would be amazing.  If you are happy to get it hosted on Vercel then I'd vote for that.

I will look further into IPFS hosting, so we have a decentralised solution for production.  I'll also look at our domain options.  We already have the XRD domain, but that currently requires our users to have the Chrome/Firefox extension to resolve dexter.xrd to our app so maybe we want to secure a web2 domain as well (dexteronradix.com for example).

**Comment by timanrebel** [comment]
NextJS is by Vercel, right? So Vercel would be a great option. And they have a free plan as well...

I have no experience with Vercel, but I can teach it myself in no time if you need help.

**Comment by Radstakes** [comment]
Excuse my lack of understanding of development, but is it possible to export DeXter as a static website?  I can only deploy it by running the node engine, is this correct?  I was hoping to build it and export as static html pages that we could then host on IPFS, but I couldn't get it to work,  Am I doing something wrong, or is this just the nature of a nodejs app?

**Comment by EvgeniiaVak** [comment]
@Radstakes it is possible to export as a static site if running `npm i` followed by `npm run build` (for example locally on your machine) - it will result in files that can be used the way you want. Alternatively you can wait until we set up a ci here in github, that will result in the static files (for example in releases).

**Comment by Radstakes** [comment]
Yeah I did try that and it compiled successfully but it didn't generate any static html files.  Maybe something else I need to configure in the next.config.js but I haven't figured it out yet.  It seemed to me that you still need to run the nodejs web server to render the site, which rules out IPFS deployment.

**Comment by EvgeniiaVak** [comment]
@Radstakes ah, yes, sorry, forgot this line in the settings https://github.com/DeXter-on-Radix/website/pull/67/files

**Comment by Radstakes** [comment]
OK so updating the config attempts to export static files, but there's some pre-render issues currently preventing the pages being generated: [prerendor-error](https://nextjs.org/docs/messages/prerender-error)

I'm not sure what the error is, do any of our pages require server side rendering?  Maybe best I wait until we're closer to a release for testing?

**Comment by EvgeniiaVak** [comment]
@Radstakes yes, we'll need to have a closer look to the build process with the current version, we'll need the ci anyways (regardless of where we host the resulting files), tracking it in #36 planning to do it this weekend

**Comment by EvgeniiaVak** [comment]
@Radstakes the build on main branch is working now, you can try again with `npm run build` and the resulting `out` folder if you want. 
Warning: it's quite ugly (no styles applied) and the position size %s shortcut do not work correctly yet.

**Comment by Radstakes** [comment]
Thanks @EvgeniiaVak - Just tried my first trades on DeXter, but sadly had to build it using npm run dev.  When I use npm run build, it compiles OK and produces an 'out' directory but when I try to view the index.html I just see this...

![image](https://github.com/DeXter-on-Radix/website/assets/83462165/37f691f4-17db-4642-8330-f0b62d43e8c3)

Using run dev works fine for testing locally though, this is what I get...

![image](https://github.com/DeXter-on-Radix/website/assets/83462165/ac3c851f-13c2-4e81-bbd8-b68c558ee1e8)

It's connecting fine and executing trades is working great.  One question I have on the manifest, what's the second output shown here?

![image](https://github.com/DeXter-on-Radix/website/assets/83462165/a9ee1969-7bb8-4db4-a074-7ab154900cc9)

**Comment by EvgeniiaVak** [comment]
@Radstakes ah, this is because you need some server that knows how to respond to the pages requests. All the cloud providers do (I'll probably push something to vercel later today or tomorrow). The local OS unfotunately doesn't (it serves you the html you clikced all right, but all the other files like js and css - no). 
I'm not sure about IPFS, never tried it, very interested to see how that would go. 
Locally you can serve the build files with `npx serve out` (it'll ask you to install the serve thing if you don't have it yet) or if you have python istalled you can use its built-in server:
```
cd out
python3 -m http.server
```

**Comment by Radstakes** [comment]
thanks @EvgeniiaVak - that was my concern, as IPFS is just file storage, anything that requires a server to run is not going to work there.  I think Fleek might be an option so will look into that, otherwise we will need a web2 server to host the site, which is not ideal, but I guess will be fine for the MVP.  We can still provide instructions for people to run the front end locally if they want a completely decentralised experience.

**Comment by Radstakes** [comment]
Update @EvgeniiaVak - managed to host the website using Fleek.  So we're now on IPFS and any updates to main will automatically redeploy.  Pretty cool - if you want to test it, here's the link: [](https://purple-grass-3772.on.fleek.co)

I also had a chat with Wylie, he thinks the issues I'm having with the static deployment is because SSR is still enabled. There's a flag you need to specify at build for static generation apparently.  He's going to pull the repo and try and troubleshoot it for us.

Fleek will work fine for us, but even better if we can get the static deployment working and host it on IPFS manually too.

**Comment by EvgeniiaVak** [comment]
Yes, we have SSG, which is something like SSR but for generating static sites. It will be helpful later for SEO and performance, but currently we don't use that much. I'm very interested in other people reviews of this 👍

**Comment by Radstakes** [comment]
I've created a subdomain and linked it to the deployed site (will need to use an IPFS ready browser like Brave): ipns://dev.dexteronradix.com/

Will be good to test if it updates automatically the next time some revisions are committed.

**Comment by EvgeniiaVak** [comment]
@Radstakes 
> otherwise we will need a web2 server to host the site,

not really, there kind of can define 3 types of creating a website:
- **a single .html file** - could be opened by directly from a folder in your browser locally, for some reason the industry decided it is not the way (maybe because of performance reasons, I don't really know) but the thing is, almost no framework can build to it by default, you need to jump through hoops to achieve it, very inconvenient for small projects btw, when you just want to share a prototype with a colleague
- **static site** (this is what we have) - which is just a collection of files, (html, css, js, images etc.) and does not run any logic on the server, the only thing that is required from the server is that it's able to give that particular file for that address. 
So if the additional files (js, css, etc.) have the same domain, they should be served all right.
- **server powered app** - when some logic executes on the server, that one would really require us to have some custom server running, but we are not doing that in DeXter, all the server-side logic is covered by AlphaDEX

**Comment by EvgeniiaVak** [comment]
@Radstakes 
I guess for the sake of simplicity we will be hosting both testnet and mainnet versions on netlify for now?
What is the build process there? can we specify environment variables for the build stage?

**Comment by Radstakes** [comment]
@EvgeniiaVak yes I think that would be the easiest route. For mainnet we probably want to publish manually for safety. I'll have a look at setting environment variables too, should be able to get back onto this in a couple of days.

**Comment by Radstakes** [comment]
Hi @EvgeniiaVak - Update on hosting... Unfortunately I can't add you or any of the other team members to Netlify unless we upgrade to the Pro plan, so I would suggest that for now I retain access alone on the free tier until after we launch and hopefully then the treasury can fund the hosting costs and I can add you or anyone else as a collaborator.

In terms of build, these are the settings we currently have: 
![image](https://github.com/DeXter-on-Radix/website/assets/83462165/5e0f56ec-66c6-4bd6-b90f-eae0af4a540b) So perhaps we should create a new branch for mainnet, and set this to deploy manually?  We could auto generate a deploy_preview of mainnet releases, but only push to dexteronradix.com when we're happy. What do you think?

If there's any environment variables you want to set, I can add these quite easily.  There's some guidance in the docs here: [](https://docs.netlify.com/configure-builds/environment-variables/)

**Comment by EvgeniiaVak** [comment]
@Radstakes 

> So perhaps we should create a new branch for mainnet, and set this to deploy manually?

Yes, we can create a new branch.

> We could auto generate a deploy_preview of mainnet releases, but only push to dexteronradix.com when we're happy.

Sounds great! Do we need the new branch for this? or can this be done from the same `main` branch that deploys to test.dexter... as well, just changing the env var values?

**Comment by Radstakes** [comment]
Should we use a subdomain for the app, like `app.dexteronradix.com` or just use the root domain (`dexteronradix.com`)? We might want to have a landing page or something in future?

**Comment by EvgeniiaVak** [comment]
@Radstakes @nguvictor 
Ok, new branch it is. How should we name it? Here are a few options:
- make the `main` branch the branch for mainnet, and rename the current main branch to `develop`
- `production`
-  `mainnet`

About the subdomain, I think it's ok to have just `dexteronradix.com`, we can have the landing page on it later (when we have the page), and the current trading page we can move to `dexteronradix.com/trade`. Alternatively, if we do use subdomains, how the testnet version would look like, something like `test.app.dexteronradix.com`?

**Comment by Radstakes** [comment]
`main `for mainnet and a duplicate `develop `branch makes sense to me. 

I'm also happy to use the root domain for the app, like you say we can always change it later.  Unfortunately we can only assign one domain with the free tier on Netlify, so our production branch will use `dexteronradix.com` and the test-deploys will have to use a Netlify link.  If we later go for the paid tier, we can then use` test.dexteronradix.com` for these deploys.

**Comment by EvgeniiaVak** [comment]
@Radstakes maybe we don't even need the develop branch, while we don't have `test.dexteronradix.com` (btw, how much would it cost?), maybe what we need is to change `test.dexteronradix.com` to `dexteronradix.com` in the current deployment and that's it. We could also require at least 2 reviews before merging into `main` branch.

**Comment by Radstakes** [comment]
@EvgeniiaVak yes that would be the simplest way forward.  I can update the domain records and then when we merge into main we will be on mainnet.  I think it would be good to keep `test.dexteronradix.com` going, but at the moment we don't need a paid tier.  The Pro tier is $19/month and that will give us much more bandwidth and subdomain support.  I think ideally we would make a proposal to the DAO/treasury to cover this cost, once the treasury is a bit more healthy.

**Comment by EvgeniiaVak** [comment]
Closing this as we are hosting on Netlify. We may reopen it later if we need something else
