### ISSUE TITLE
An array of errors when fetching Quote

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#83]
Not a very pressing issue because it's blocking anything: the Quote fetching functionality works. But it would be cool to have console clean.

Happens when just loading the page:
![Image](https://github.com/DeXter-on-Radix/website/assets/27793901/70d96b95-a036-4927-bb5f-6684606bb81a)

We probably want to fetch only when all the input fields are valid and need to add validation for position size being > 0.

**Comment by SmashingBumpkin** [comment]
I'm pretty sure this is a different issue to the 4x 406 issue. This issue is just caused by sending out requests before everything has been initialized, and is solved by waiting for everything to initialize. The other issue is not caused by the inputs (other than OrderType != Market)

**Comment by EvgeniiaVak** [comment]
Maybe, but the behavior is the same, and fetching eventually works with both 400 and 406 issues. Also I asked about 406 issues (I was getting them too): here is Fred's response: https://discord.com/channels/1125689933735145503/1125689934251032584/1141743909517660210

Hi. I think that is still a mistake in the response codes for the quotes. It is giving the 406 code because the order wont be filled which is a 406 for a market order but should be a 200 for limit orders. I need to go throught he quote functionality with a fine comb tooth and make sure it handles all cases correctly. It was initially just built for market orders, but I started adjusting it to also work with limit orders. But there is still some work to be done. 😁  At least the message already tells you that it will be added to the orderbook.

**Comment by EvgeniiaVak** [comment]
cannot reproduce, probably some update on AlphaDEX or DeXter order input component fixed it.
