### ISSUE TITLE
4x 406 responses when adex.getExchangeOrderQuote() is called on limit orders

### ISSUE THREAD

**Issue by SmashingBumpkin** [DeXter-on-Radix/website#88]
In orderInputSlice, when fetchQuote is called, it sends a request to the adex API using the adex.getExchangeOrderQuote function. Even when the function call is completely acceptable (ie, adex returns "success", a 406 error is returned 4 times. This only happens with both types of limit order. Market orders do not cause it.

@fliebenberg I think this must be on the adex end.

**Comment by EvgeniiaVak** [comment]
duplicate, we already have #83 and I think it can be postponed, just because it works

**Comment by fliebenberg** [comment]
Will have a look at the multiple returns. It should only return the response *406 or other) once.
