### ISSUE TITLE
layout (position the elements on the page)

### ISSUE THREAD

**Issue by EvgeniiaVak** [DeXter-on-Radix/website#94]

**Comment by EvgeniiaVak** [comment]
@abdulhaseeb13mar I merged #99 because it makes things much better than they were, but it doesn't close this issue yet. You are probably already aware, but just in case - what I noticed:

1. for some reason the limit and order switch result in a small layout shift in components above the toggle (I tried on a 13 inch display)

    <img width="600" alt="Screenshot 2023-09-05 at 21 05 23" src="https://github.com/DeXter-on-Radix/website/assets/27793901/d7932c5f-4d82-47be-b420-80acc29eda7e">
    <img width="600" alt="Screenshot 2023-09-05 at 21 03 49" src="https://github.com/DeXter-on-Radix/website/assets/27793901/7b6e5ec4-41c0-454d-9e03-0da4db97b333">

2. paddings/margins are absent on some components

**Comment by abdulhaseeb13mar** [comment]
Yes @EvgeniiaVak , I haven't started working on these components yet. I just mapped the layout and put these components as it is inside the layout in their respective places.

Also can you tell the pixel resolution of your screen, so I will also test it in that dimension.

Regarding the point#1, I'm not sure I understood what you are saying 🤔 maybe it's something about the toggle switch of market/limit ?

**Comment by EvgeniiaVak** [comment]
@abdulhaseeb13mar It happens on other resolutions too (just tried on another screen, with custom (not full size) window).
![Screenshot 2023-09-06 at 11 10 42](https://github.com/DeXter-on-Radix/website/assets/27793901/2a4f8795-1dee-44f0-904a-1009e8fa39d8)
![Screenshot 2023-09-06 at 11 09 47](https://github.com/DeXter-on-Radix/website/assets/27793901/c02885b0-70b7-4d83-b807-9384c831d3c1)
The space between pair selector and market/limit toggle jumps, try select market and limit orders back and forth, you'll see.

**Comment by Radstakes** [comment]
Can confirm I see the same behaviour too.  It's fine for ADEX1 and ADEX2, but switching to ADEX3 causes a minor shift (1366x768 resolution), using Brave browser.

**Comment by abdulhaseeb13mar** [comment]
It's alright I'll revamp this component anyway so most probably it'll be fix.

**Comment by EvgeniiaVak** [comment]
fixed by #99
